### ISSUE TITLE
Font quality is lower on some pages of PDFs

### ISSUE THREAD

**Issue by gingerbeardman** [koreader/koreader#10879]
* KOReader version: 2023.08
* Device: Nexus 7 (2013) 32-bit device
* Running LineageOS 18.1 (Android 11)

#### Issue
- fonts on some pages appear at lower quality

#### Steps to reproduce
- [Prince of Persia PDF](https://github.com/koreader/koreader/issues/10879#issuecomment-1708341706)

#### Comparison

![Screenshot_20230906-012527_KOReader](https://github.com/koreader/koreader/assets/49612/39928ef6-3b96-4938-9b36-12da5b0e78e8)

![Screenshot_20230906-012541_KOReader](https://github.com/koreader/koreader/assets/49612/42b3865e-4d6a-4833-9286-1d2b9b83d53a)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by gingerbeardman** [comment]
Comparison at 5x zoom

![Screenshot_20230906-013914_KOReader](https://github.com/koreader/koreader/assets/49612/3aca1aa2-fd1a-47ab-87b6-74ab19ef78ff)

![Screenshot_20230906-013813_KOReader](https://github.com/koreader/koreader/assets/49612/75e920d1-a222-474a-9dfc-8b7bec6dbc14)

**Comment by benoit-pierre** [comment]
And you don't see the same issue with another PDF reader?

**Comment by NiLuJe** [comment]
Is reflow involved at all (I assume no, since it's currently horribly crashing on arm64 Android builds ;p).

**Comment by gingerbeardman** [comment]
One thing I did notice is that the affected pages all have images included on them.

https://pdfcoffee.com/making-of-prince-of-persia-pdf-free.html

Could KOR be displaying a bitmap alternative to the page rather than the page with vector fonts? I'm not entirely sure how 

> Is reflow involved at all?
No reflow.

> And you don't see the same issue with another PDF reader?
No, not as far as I have tested.

No problem, all good, in th following apps:
- Acrobat Reader
- Moon+ Reader
- PocketReader
- ReadEra
- Preview (macOS)
- Acrobat Pro (macOS)

Inconclusive (each page of PDF is converted to low-res bitmap):
- CDisplayEx
- Librera FD

**Comment by gingerbeardman** [comment]
Thanks for the detective work!

- 1.13.0 was released April 2018, so is very old.
- 1.23.2 was released last week.
- 1.23.3 was released less than two days ago.

**Comment by gingerbeardman** [comment]
One more thing:

> arm64 Android

My device is 32-bit

**Comment by Gabriel85** [comment]
> I can reproduce the issue with the official 2023.06.1 Appimage, but not with my custom build (with an updated MuPDF library, among other things). So probably a MuPDF bug (master is using 1.13.0, upstream is at 1.23.3, my build is using 1.23.2).

Do you have a 32-bit APK of that build? I am having several other issues and I am suspecting they have been fixed upstream a long time ago.

**Comment by benoit-pierre** [comment]
> > I can reproduce the issue with the official 2023.06.1 Appimage, but not with my custom build (with an updated MuPDF library, among other things). So probably a MuPDF bug (master is using 1.13.0, upstream is at 1.23.3, my build is using 1.23.2).
> 
> Do you have a 32-bit APK of that build? I am having several other issues and I am suspecting they have been fixed upstream a long time ago.

See [here](https://github.com/benoit-pierre/koreader/actions?query=branch%3Abpierre+is%3Asuccess%2b).

**Comment by gingerbeardman** [comment]
I still see this problem
- official 2024.10 Ovis 
- latest build artefact in cork of @benoit-pierre

**Comment by gingerbeardman** [comment]
Cheers!
