### ISSUE TITLE
[calibre.koplugin]: Crash when inbox folder name contains '&'

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#12412]
* KOReader version: 2024.07-131
* Device: Kobo Sage, Kobo Libra 2

#### Issue
So for example if the chosen inbox folder is named 'a & b' or 'a&b', Calibre plugin crashes when I try to connect.

[crash.log](https://github.com/user-attachments/files/16751667/crash.log)

**Comment by Commodore64user** [comment]
Sorry to be the one who states the obvious but, why don't you remove the ampersand?

**Comment by gerhaher** [comment]
Don't worry, I have. 

I supposed it is a bug so I wanted to report it.

**Comment by Frenzie** [comment]
Could you check if it's fixed with this?

```diff
diff --git a/frontend/util.lua b/frontend/util.lua
index ddf2b906c..fc36062ea 100644
--- a/frontend/util.lua
+++ b/frontend/util.lua
@@ -858,7 +858,7 @@ end
 function util.diskUsage(dir)
     -- safe way of testing df & awk
     local function doCommand(d)
-        local handle = io.popen("df -k " .. d .. " 2>/dev/null | awk '$3 ~ /[0-9]+/ { print $2,$3,$4 }' 2>/dev/null || echo ::ERROR::")
+        local handle = io.popen("df -k '" .. d .. "' 2>/dev/null | awk '$3 ~ /[0-9]+/ { print $2,$3,$4 }' 2>/dev/null || echo ::ERROR::")
         if not handle then return end
         local output = handle:read("*all")
         handle:close()
```

**Comment by benoit-pierre** [comment]
Still does not handle `'` in the directory, no? Need a shell escape function:

```lua
function util.shellEscape(text)
    return "'" .. text:gsub("'", "'\\''") .. "'"
end
```

**Comment by Commodore64user** [comment]
> Don't worry, I have. 
> 
> I supposed it is a bug, so I wanted to report it.

Right. I thought you were unable to use it in the meantime.

**Comment by Frenzie** [comment]
> Still does not handle ' in the directory, no? 

Well sure, one might even make that dependent on an `if text:match("[^a-zA-Z0-9/-_]")` or something along those lines (though that's probably a silly micro-optimization), but all of that is rather besides the point of getting a diagnosis.

**Comment by Frenzie** [comment]
By which I mean "can you change this one line real quick" is much more effective for debugging imo. ;-)

**Comment by gerhaher** [comment]
> Could you check if it's fixed with this?
> 
> ```diff
> diff --git a/frontend/util.lua b/frontend/util.lua
> index ddf2b906c..fc36062ea 100644
> --- a/frontend/util.lua
> +++ b/frontend/util.lua
> @@ -858,7 +858,7 @@ end
>  function util.diskUsage(dir)
>      -- safe way of testing df & awk
>      local function doCommand(d)
> -        local handle = io.popen("df -k " .. d .. " 2>/dev/null | awk '$3 ~ /[0-9]+/ { print $2,$3,$4 }' 2>/dev/null || echo ::ERROR::")
> +        local handle = io.popen("df -k '" .. d .. "' 2>/dev/null | awk '$3 ~ /[0-9]+/ { print $2,$3,$4 }' 2>/dev/null || echo ::ERROR::")
>          if not handle then return end
>          local output = handle:read("*all")
>          handle:close()
> ```

Yes, it did. No crashes anymore.

Thanks!

**Comment by Frenzie** [comment]
In that case what @benoit-pierre proposed (or something much like it) will be the proper solution. ^_^

**Comment by pazos** [comment]
Fixed by https://github.com/koreader/koreader/pull/13448
