### ISSUE TITLE
Nightly gbf290e0c2 crashes on Android 9 and 10

### ISSUE THREAD

**Issue by Steven630** [koreader/koreader#12522]
* KOReader version: nightly (gbf290e0c2_2024-09-14)
* Device: Android 9 and 10

#### Issue

Crashes on start on both my Android 10 and 9 device. With Android 9, it actually tried to launch for a few seconds before the Android system telling me multiple attempts had failed. On Android 10, it just crashed instantly.

I uninstalled the stable version before installing the nightly.

No issue with 2024.07 stable

I want to try out the update on Vocabulary Builder : (

**Comment by Steven630** [comment]
> need the crash log

There was no crash log under the Koreader folder (I had enabled verbose logging).

**Comment by hugleo** [comment]
Need external tool adb

try something like:
adb logcat KOReader:V luajit-launcher:V dlopen:V "*:E"

**Comment by 0zd3m1r** [comment]
![IMG_20240925_192003.jpg](https://github.com/user-attachments/assets/6dfe1994-5e52-4089-83c5-f1bed5f96e73)

is it same problem?

**Comment by benoit-pierre** [comment]
No, this look like fallback from #12486. Please create a dedicated issue with all the details.

**Comment by 0zd3m1r** [comment]
> No, this look like fallback from #12486. Please create a dedicated issue with all the details.

Fixed #12553. Thanks.

**Comment by Steven630** [comment]
gcba79bca1_2024-10-02 still crashes on start on Android 10. Have not tried on Android 9 yet.

I have not used adb. Will give more info when I use that tool.

**Comment by pazos** [comment]
@Steven630: uninstall, install latest nightly, **don't open yet**, rename /sdcard/koreader to /sdcard/koreader-old, start the app.

Could you reproduce the crash? You should not :)

**Comment by Steven630** [comment]
> @Steven630: uninstall, install latest nightly, **don't open yet**, rename /sdcard/koreader to /sdcard/koreader-old, start the app.
> 
> Could you reproduce the crash? You should not :)
> 
> 

I did what you said. With the latest nightly (gf0e5acfd2), I was able to see this screenshot (telling me that it will use colors and  is opening the quickstart) before it crashes:

![Screenshot_20241006_231411.jpg](https://github.com/user-attachments/assets/6b9a619f-287a-4bbb-aeec-a12ad17358b5)

**Comment by benoit-pierre** [comment]
How come it did not start in English? Are you sure you rename the old `/sdcard/koreader` directory before starting?

**Comment by benoit-pierre** [comment]
Does the Android version detect the locale?

**Comment by Steven630** [comment]
> How come it did not start in English? Are you sure you renamed the old `/sdcard/koreader` directory before starting?

Yes, I renamed it. There are both "koreader-old" and "koreader" folders under the sdcard directory:

![Screenshot_20241006_235720.jpg](https://github.com/user-attachments/assets/8b1580c8-df94-46f4-9c69-103bdfce5569)

![Screenshot_20241006_235753.jpg](https://github.com/user-attachments/assets/5c65d084-c427-4809-afe2-83aeaccc662d)

**Comment by benoit-pierre** [comment]
Please provide a log. Use `adb logcat`.

**Comment by Steven630** [comment]
> Please provide a log. Use `adb logcat`.

OK. I will try that when I have my laptop with me.

**Comment by pazos** [comment]
> I did what you said.

**Comment by Steven630** [comment]
> 
> Please do it again in strict order, @Steven630 

I 

1. uninstalled yesterday's nightly version

2. deleted the "koreader" folder, but kept "koreader-old" folder

3. installed nightly g93935f34e_2024-10-06/

4. opened the app

It still shows the same Chinese message before crashing.

![Screenshot_20241007_234104.jpg](https://github.com/user-attachments/assets/faea76cd-58a3-47c5-b421-0db4ec7ce0b1)

**Comment by jonnyl2** [comment]
I can reproduce this issue on a Boox Nova 2 (Android 9). Current nightlies don't run anymore. The app appears to crash while trying to open the quickstart guide (infomessage as above, only in English and no other box in the background), and then abruptly closes without notice.

Adb log:
[lognova2.txt.zip](https://github.com/user-attachments/files/17349965/lognova2.txt.zip)

**Comment by benoit-pierre** [comment]
@jonnyl2: and with the build mentioned [here](https://github.com/koreader/koreader/issues/12613#issuecomment-2403423474)?

**Comment by jonnyl2** [comment]
Is there an apk available?

**Comment by benoit-pierre** [comment]
Just rename the extension to `apk`.

**Comment by jonnyl2** [comment]
This one installs and opens fine, yes :+1:

**Comment by Steven630** [comment]
> @jonnyl2: and with the build mentioned [here](https://github.com/koreader/koreader/issues/12613#issuecomment-2403423474)?

This one also does not crash for me.  Strangely, it still shows Chinese on the first start even though I have uninstalled the old nightly and deleted the "koreader" folder before installing this build.
