### ISSUE TITLE
FR: Cancel book opening

### ISSUE THREAD

**Issue by gd4c** [koreader/koreader#13184]
**Does your feature request involve difficulty completing a task? Please describe.**

Normally, I want to continue reading on app launch (open with last file).

Occasionally I want to access another file. If the current file is big, I have to wait many seconds (10s of sec) for it to load so that I can switch to the desired file.

**Describe the solution you'd like**

A button that cancels the opening, going to history or file manager.

**Comment by Commodore64user** [comment]
fixed by #15024

**Comment by jonnyl2** [comment]
Not really fixed. It's not just about accidentally opened books, but also (if not primarily) about books that unexpectedly take a long time to open.

**Comment by gd4c** [comment]
I second @jonnyl2 . Even if I enable "Ask to open". It is a bit annoying to have it on by default so I will inevitably (and unfortunately) form the muscle memory of tapping the book then tapping OK without looking. Square 0

**Comment by poire-z** [comment]
Would have asked if tihs was mainly happening with large EPUBs, or also with PDF (no real experience with large PDFs), as I had an idea:
Just do as Trapper does when saving Wikipedia EPUBs, giving control from time to time to UIManager to catch a dismiss on the "Opening..." InfoMessage, as crengine while loading the book calls a callback into frontend reporting loading progress, which allows us to show the loading progress bar in the top left:

```diff
--- a/frontend/apps/reader/modules/readerrolling.lua
+++ b/frontend/apps/reader/modules/readerrolling.lua
@@ -1293,2 +1293,3 @@ function ReaderRolling:handleEngineCallback(ev, ...)
     local arg = argc > 0 and select(1, ...)
+    local cancel = self.ui.checkIfOpeningCancelled()
     -- logger.info("handleCallback: got", ev, ...)
--- a/frontend/apps/reader/readerui.lua
+++ b/frontend/apps/reader/readerui.lua
@@ -668,3 +668,3 @@ end
 function ReaderUI:showReaderCoroutine(file, provider, seamless)
-    UIManager:show(InfoMessage:new{
+    self._opening_infomsg = InfoMessage:new{
         text = T(_("Opening file '%1'."), BD.filepath(filemanagerutil.abbreviate(file))),
@@ -672,3 +672,10 @@ function ReaderUI:showReaderCoroutine(file, provider, seamless)
         invisible = seamless,
-    })
+        dismiss_callback = function()
+            local _coroutine = coroutine.running()
+            if _coroutine then
+                coroutine.resume(_coroutine, false)
+            end
+        end,
+    }
+    UIManager:show(self._opening_infomsg)
     -- doShowReader might block for a long time, so force repaint here
@@ -695,2 +702,60 @@ end

+function ReaderUI:checkIfOpeningCancelled()
+    if not coroutine.running() then
+        return false
+    end
+    logger.warn("coroutine running")
+    local go_on = true
+    local go_on_func
+    go_on_func = function() coroutine.resume(_coroutine, true) end
+    -- delay matters: 0.05 or 0.1 seems fine
+    -- 0.01 is too fast: go_on_func is called before our dismiss_callback is processed
+    UIManager:scheduleIn(0.1, go_on_func)
+
+    go_on = coroutine.yield() -- gives control back to UIManager
+    -- go_on is the 2nd arg given to the coroutine.resume() that got us resumed:
+    -- false if it was a dismiss_callback
+    -- true if it was the schedule go_on_func
+    if not go_on then -- dismiss_callback called
+        UIManager:unschedule(go_on_func) -- no more need for this scheduled action
+        -- Don't just return false without confirmation (this tap may have been
+        -- made by error, and we don't want to just cancel a long running job)
+        local abort_box = ConfirmBox:new{
+            text = self.paused_text and self.paused_text or _("Paused"),
+            -- ok and cancel reversed, as tapping outside will
+            -- get cancel_callback called: if tap outside was the
+            -- result of a tap error, we want to continue. Cancelling
+            -- will need an explicit tap on the ok_text button.
+            cancel_text = self.paused_continue_text and self.paused_continue_text or _("Continue"),
+            ok_text = self.paused_abort_text and self.paused_abort_text or _("Abort"),
+            cancel_callback = function()
+                coroutine.resume(_coroutine, true)
+            end,
+            ok_callback = function()
+                coroutine.resume(_coroutine, false)
+            end,
+            -- flush any pending tap, so past events won't be considered
+            -- action on the yet to be displayed widget
+            flush_events_on_show = true,
+        }
+        UIManager:show(abort_box)
+        -- no need to forceRePaint, UIManager will do it when we yield()
+        go_on = coroutine.yield() -- abort_box ok/cancel from their coroutine.resume()
+        UIManager:close(abort_box)
+        if not go_on then
+            UIManager:close(self._opening_infomsg)
+            UIManager:forceRePaint()
+            return true
+        end
+        if self._opening_infomsg then
+            self._opening_infomsg:init()
+            UIManager:show(self._opening_infomsg)
+        end
+        UIManager:forceRePaint()
+    end
+    -- go_on_func returned result = true, or abort_box did not abort:
+    -- continue processing
+    return false
+end
+
 function ReaderUI:doShowReader(file, provider, seamless)
```

But I met this fundamental limitation in Lua/LuaJIT:

`WARN  cre callback() error: frontend/apps/reader/readerui.lua:715: attempt to yield across C-call boundary`

https://stackoverflow.com/questions/8459459/lua-coroutine-error-tempt-to-yield-across-metamethod-c-call-boundary

Anyway, even if this had worked, I would have no idea on how to abort and clean crengine loading... (except exiting KOReader, and we don't have auto restart on all platforms).

**Comment by Frenzie** [comment]
> Would have asked if tihs was mainly happening with large EPUBs, or also with PDF (no real experience with large PDFs), as I had an idea:

Large PDFs still load primarily page by page so it's a bit different than EPUB in that sense. Of course a similar effect could still happen if you have very large or otherwise heavy individual pages.
