### ISSUE TITLE
Highlight not shown while selecting DjVu text

### ISSUE THREAD

**Issue by Geremia** [koreader/koreader#14569]
### Device

Android

### KOReader version

2025.08

### Model and firmware version

ONYX Leaf 2023-12-12_23-00_3.5_4687b1901

### Issue description

Selecting text in [this djvu book](https://archive.org/download/educationofthefo028335mbp/educationofthefo028335mbp.djvu) doesn't show a highlight (except the first word or few characters where mouse-down occurs) while selecting (the word where mouse-up occurs never highlights at all). If the "Highlight" button is pressed, it shows the selected text (cf. 00:18 of video below), though it skips some words or characters sometimes, and the associated bookmark for the highlight doesn't show the selected text (cf. 00:07 of video below; all the highlights lack text).

https://github.com/user-attachments/assets/d9cae781-710c-4014-a77b-c4b2c6e3be9b

I don't have any problem selecting text in this DjVu in [Okular](https://okular.kde.org).

### Steps to reproduce

1. Open [educationofthefo028335mbp.djvu](https://archive.org/download/educationofthefo028335mbp/educationofthefo028335mbp.djvu).
2. Try to select text; it won't highlight until the "Highlight" button is pressed. No highlights shown while highlighting (except the first word or characters around where mouse-down occurs, sometimes).

**Comment by Frenzie** [comment]
Fixed in #14350.

**Comment by Geremia** [comment]
@Frenzie Yes, that fixes it for new highlights, but the previous ones still don't have text.

**Comment by Frenzie** [comment]
Highlights are what they are at the time they're made. They don't change afterwards.

**Comment by Geremia** [comment]
@Frenzie I guess I'll have to recreate them again, then.
