### ISSUE TITLE
Status bar overlaps text

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#1895]
* KOReader version:
v2015.11-3-g9e0be45
* Device:
Kindle 7th generation, firmware 5.7.2.1

#### Issue
Status bar overlaps text

#### Steps to reproduce
When reading PDF file with "fit content" enabled, status bar is displayed over the text. I had to turn off status bar completely to deal with it.

**Comment by houqp** [comment]
Confirmed in page mode. @ilyats , it should not be an issue in scroll mode though.

**Comment by chrox** [comment]
Fixed in #2079.

**Comment by ilyats** [comment]
Problem still exist. One way to circumvent it is to set "Margin" book option to "Large"
