### ISSUE TITLE
Statistics plugin is not keeping track properly

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1941]
- KOReader version: koreader-nightly-20160323
- Device: C67ML
#### Steps to reproduce

Open a book and read for a while

Hi

I have been reading a book (pdf) for a while and I wanted to see if the stat plugin works. Well it does not seem so. The stat page shows that I am done reading %30 of the book but shows only a  minute or so for reading. I have started reading the book yesterday.

I am wondering if this plug in does some basic time calculation based on the book's modification date (instead of some internal database), if so that would not work in case of synched folders. For instance if the user is using Syncthing or Btsync etc for this plugin, the app might modify the time data of the files.

**Comment by Frenzie** [comment]
Could you be exceeding the default timeout? See [here](https://github.com/Frenzie/koreader/blob/master/plugins/statistics.koplugin/main.lua#L116).

**Comment by gerroon** [comment]
@Frenzie 

No idea.

The weird thing is that firt time I looked at the stat page, it said 2 minutes something. Then I thought that maybe restarting Koreader might fix the wrong time. However after restarting, the stat window showed couple seconds, the previous minutes were gone.

**Comment by Frenzie** [comment]
Hm, weird. Anyway, I haven't paid much attention to it myself, but checking some books I've read shows things like a reading time of 4 hours.

**Comment by gerroon** [comment]
@Frenzie 

Well it seems to me that it resets the counter everytime I restart Koreader

**Comment by houqp** [comment]
The plugin does time calculation based on the actual time you spent reading on the page, not the file stats:  https://github.com/koreader/koreader/blob/master/plugins/statistics.koplugin/main.lua#L353

This is happening to all your books? Can you check the book setting file after you close the book to see if the config got updated properly? You should be able to find a `total_time_in_sec` entry somewhere.

**Comment by KenMaltby** [comment]
If I look at the "Book status" page the "Time" in the statistics section changes oddly, when I leave and come back. The rest seems right.

**Comment by gerroon** [comment]
TO me, the book status page keeps "adding" new numbers everytime I click on it. For instance I open a book, couple min later it shows 3:20, I click on it again in less than 5 secs, it shows 6:xx something then I open it in less than 10 secs it shows 10:xx something. So whatever it is, it is totally inconsistent and it does not make any sense.

**Comment by houqp** [comment]
@gerroon your issue is the same as @KenMaltby's. I have fixed it in #1942

**Comment by gerroon** [comment]
@houqp 

thanks

**Comment by gerroon** [comment]
@houqp 

I still have this issue with koreader-nightly-20160413 on Android Lollipop.

**Comment by houqp** [comment]
@gerroon, I cannot reproduce this the always increasing book status issue on my side anymore. I apologize if you already double checked this, but have you verified that you are testing with the new KOReader, not the old one that was running in the background?

**Comment by houqp** [comment]
Oh wait, @gerroon, in your previous comment, are you referring to the bug in the statistics page or the book status page? I only fixed the bug in book status.

**Comment by gerroon** [comment]
@houqp 

I am not sure which one refers to which but I see no fix in the book sttaus page. It shows the correct percentage but the rest of the stats are wrong, in fact the statistics page is wrong as well. The "current book" shows 0s all the way.

**Comment by gerroon** [comment]
Hi

Just letting you know that this is still an issue with  koreader-nightly-20160427, the numbers see, to reset with pdfs. I do not have an epub to test here atm.

thanks

**Comment by houqp** [comment]
@gerroon I am still not able to reproduce in emulator and my kobo. I wonder if it has anything to do with the book settings. Can you upload your book with its settings here for me to test?

**Comment by gerroon** [comment]
@houqp 
I can try it later.

**Comment by gerroon** [comment]
@houqp 

I tried many pdfs, it resets the stats everytime I start reading the books. I am C67ml and couple other android tablets.

**Comment by gerroon** [comment]
Hi

This is still an issue with pdf files. I only use pdfs so maybe I am always hitting corner cases. I tried this on 3 different Android devices with no luck.

**Comment by chrox** [comment]
I cannot reproduce this neither on Android nor on Kindle Voyage and I also mostly read PDFs. Could it be that your SD card where your PDF documents are stored are read only mode? In that case Koreader cannot write progress info to the sdr folder, considering you have another problem with sdr in #1962. I suggest you check the document lua file inside the sdr folder of your document before and after several minutes of reading; preferably post the lua files here so that others could investigate. You know that Koreader runs on different platforms configured with various environments, some users may encounter issues that others will never meet. So please provide as much information as you can to help others investigate into this if you want it to be solved.

**Comment by robert00s** [comment]
We have new statistics plugin (#2893) so we can close it now.
