### ISSUE TITLE
Koreader opens the book but it is not  properly refreshing during initial opening

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1955]
- KOReader version:koreader-nightly-20160323
- Device: C67ML
#### Issue

When I open a book in Koreader, the book opens but no  refresh is done initially so only thing I see is loading window unless I press anywhere on the screen which forces a refresh I belive
#### Steps to reproduce

Open a book in C67ML

This has been going on for a while but it is bothersome enough that I decided to report it finally.

**Comment by gerroon** [comment]
The most recent version seems to be abit better but does not resolve the issue fully.

**Comment by mwozny123** [comment]
Already reported https://github.com/koreader/koreader/issues/1949?

**Comment by gerroon** [comment]
@mwozny123 

This is differetn. This is about about not refreshing the eink page during startup. The book loads but it does not refresh the page. I can only get it refresh by clicking on any place on the screen

**Comment by houqp** [comment]
I feel like this might be a pocket book specific issue. Anyone experiencing this in other devices? I am not able to reproduce this at all from my side.

**Comment by gerroon** [comment]
Mine is Boox Android 4.2.2

**Comment by gerroon** [comment]
Any ideas on how to fix this? This is so dreadful ;( This might have been intorduced in last couple versions. I do not remember it being this bad. I literally have to press on multiple places on the screen to get the initial refresh going so that the page shows up properly.

**Comment by houqp** [comment]
I really have no clue on why this is happening :( Will you be able to find out the last working version?

**Comment by robert00s** [comment]
@gerroon 
Can you check with latest version (v2015.11-1303-gd23d016)?

**Comment by Frenzie** [comment]
Should be fixed by https://github.com/koreader/android-luajit-launcher/pull/64 and #3319.

**Comment by mk-f** [comment]
This (as well https://github.com/koreader/koreader/issues/1949) still happens on the PocketBook Inkpad. The delay does not occur always, most of the time after complete 'shutdown' and restart. 

[debug-log startup with delay](https://github.com/koreader/koreader/files/1410040/crash_bug.log)
[debug-log startup without delay](https://github.com/koreader/koreader/files/1410041/crash_nobug.log)

**Comment by Frenzie** [comment]
@mk-f It certainly sounds like similar symptoms, and the cause might even be similar on a conceptual level (e.g., something involving a compositor), but I can assure you that this Android issue is completely Android-exclusive. Could you please open a new ticket for PocketBook?

Also I don't really know how to help with PocketBook, unfortunately. Have you tried something like a basic strace?

PS It should be easy to create a build with debug symbols by using `KODEBUG=1 ./kodev build pocketbook` but you'll have to clean it first. (I want to have a separate -debug suffix but I only added this debug switch recently in <https://github.com/koreader/koreader-base/pull/525>; one thing at a time ;-)). You could also think about getting gdbserver on the device if you really want to get into it.

PPS You could also have a look at this Android memory allocation hack for LuaJIT: https://github.com/koreader/android-luajit-launcher/blob/bd885618d058e96dbef35e744cbff1b6c2c4048b/assets/android.lua#L1-L22

It's only because of the way Android does memory management but who knows…

Incidentally, there's also this which I added as a compile-time environment variable because it's useful for Valgrind should you want to get into that: https://github.com/koreader/koreader-base/blob/c06ed9653ab30003c46aad7997cdf84a5d7fa5b2/thirdparty/luajit/CMakeLists.txt#L20

I haven't really experimented with how much slower it feels in practice. But on Android some people have reported having to wait a really long time because the memory allocation gets stuck trying to find a little bit of free memory. Something similar could be going on.

It's a pity (and a blessing I'm sure!) that reproducing this is very difficult. Hopefully some of this was helpful.

**Comment by mk-f** [comment]
Thanks. I'll open a new issue, once i have a useful strace-log or gdb-backtrace. I actually did format the internal drive because of some unrelated issues and since then (and with a new debug-build) the delay did not occur until now. On the other hand, that may be just luck, i observed that behavior in the past.
