### ISSUE TITLE
Compatibility with StarDict 3.0.0 dictionaries?

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#1994]
* KOReader version: v2015.11-371-g24a30cb
* Device: Kobo Glo HD

Cannot use stardict dictionnaries downloaded here: http://download.huzheng.org/babylon/french/ On the webpage, it says "Notice, only StarDict-3.0.0 and above version support these dictionaries."
Is Koreader compatible with them ? Or maybe these files don't respect the Stardict file format? Or maybe they're too big?

After unzipping them, decompressing the .dict.dz file and copying the folder in the ".adds\koreader\data\dict" folder, they don't appear when I make a long press on a word (but 2 other ones, previously installed are working well).

That's so bad: here are the only english-french dictionaries I found at this time, and I'd like so much to read english novels in their own language.

**Comment by houqp** [comment]
Yup... Looks like we are still using 0.4.2...

**Comment by NiLuJe** [comment]
Note that I don't know if sdcv 0.5.whatever_beta fares much better on that front.

**Comment by Frenzie** [comment]
I just tried 0.5.0_beta4 from the Debian repo and those dics work.

**Comment by Brnoch** [comment]
That's a great news... Do you think you can implement this new version in Koreader?

**Comment by Frenzie** [comment]
The two have diverged slightly, but I'll take a preliminary look to see if a merge would be doable without really diving into the code.

**Comment by Brnoch** [comment]
Thanks Frenzie, I really appreciate!

**Comment by Frenzie** [comment]
Hm, I can't quite seem to figure out the correct workflow here. 

I suppose one could do something like this and look at it all manually.

```
git svn clone svn://svn.code.sf.net/p/sdcv/code/trunk sdcv_svn
git clone git@github.com:Frenzie/sdcv.git
cd sdcv
git checkout -b initial 23eda3e
git pull ../sdcv_svn/
```

But it seems like some kind of cherry picking in one direction or the other might be more appropriate.

**Comment by Brnoch** [comment]
I wish I could help you, but I'm only a Windows developper...

**Comment by houqp** [comment]
We can't really cherry pick in this case since it's svn :( We just have to suck it up and apply the diff manually.

Alternatively, you can generate a diff in svn, then apply it to our git fork. This way is less painful I think.

**Comment by houqp** [comment]
@Brnoch you know KOReader runs on Windows too right? ;P

**Comment by Brnoch** [comment]
@Qingping Hou : I forgot as I failed to install Windows on my Kobo ;P

2016-04-29 0:29 GMT+02:00 Qingping Hou <notifications@github.com>:

**Comment by Frenzie** [comment]
@houqp There is absolutely no problem cherry picking with the Git SVN bridge. ;) One problem I ran into is that the original import was a snapshot of all files rather than a conversion from SVN. (Bad @chrox =P) I'll probably take another look at it later to see if I can figure out something creative with rebase and branches but of course most if not all of our patches here should probably be applied upstream anyway.

**Comment by houqp** [comment]
Interesting, I don't know that's supported :) It will definitely be nice if our patches can be contributed back to upstream.

**Comment by Frenzie** [comment]
Dunno how to contrib to sourceforge though :p
On Apr 30, 2016 7:41 AM, "Qingping Hou" <notifications@github.com> wrote:

Interesting, I don't know that's supported :) It will definitely be nice if
our patches can be contributed back to upstream.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/koreader/koreader/issues/1994#issuecomment-215940141>

**Comment by Frenzie** [comment]
I'm closing this now since I fixed it, but unfortunately it won't show automatically show up in a nightly build until something changes on the main koreader repo.

**Comment by Brnoch** [comment]
Thanks a lot! 
I'll wait patiently for the change to show up.
Will it still be necessary/recommended to decompress the .dict.dz file with this new version ?

**Comment by Frenzie** [comment]
It's long since there in the nightlies. ;) for the rest nothing changed.

**Comment by Brnoch** [comment]
On my Kobo, new dictionnaries didn't show up after the upgrade.
I'll check tonight that I did proceed correctly. Shall I copy once again the dictionnaries in the "dict" folder so that Koreader processes them once again ?

**Comment by Frenzie** [comment]
You simply extract the whole archive, so your /dict looks like

/dict/stardict-SomeDictionary-1.0

Afaik there should be no need to to anything else. Could you clarify this bit about decompressing the .dict.dz file?

The nightly update seems to be messing up on my device atm. If something failed you'd best upgrade manually, particularly the sdcv executable in the main /koreader directory but I'd just do the whole thing.

**Comment by Frenzie** [comment]
Hm, I can confirm that it doesn't seem to work with the koreader-nightly-20160513, even though it should. OTA isn't working for me from that build either. @houqp Do you have any idea what's up?

**Comment by Brnoch** [comment]
For information : I read somewhere that the .dict.dz are compressed and that it's better to de-compress them. Under Windows, you can de-compress them after renaming the file to dict.gz. That's what I've done

**Comment by Frenzie** [comment]
Sure, but what's the rationale? :) Low-memory devices?

**Comment by Brnoch** [comment]
Well, actually, I don't know :-) 
I figured first that this could help to solve the problem with the new dictionaries, and then to make the system snappier...

**Comment by AlanSP1** [comment]
I needed to decompress my dictionary file to have dictionary working. It was on older koreader versions, not sure how it should work on latest.

**Comment by KenMaltby** [comment]
I have a couple of dictionaries the use a ".dict.dz"  file and work fine in my AuraHD under KOReader. (v2015.11-396)  They have been working, as far as I know, for many past versions.

**Comment by Frenzie** [comment]
@AlanSP1 Would this have been on Android by any chance? Android is… special. =P Things there aren't really indicative of what's up. Compression-wise I don't think there should be any difference since dictionary support was first added in 2013.

**Comment by AlanSP1** [comment]
I have Kobo H20.

But, now thinking, maybe I remember it wrongly? Maybe I was trying to use StarDict3 dictionary? Anyway, I am sure I decompressed StarDict2 dictionary and it works. I had problems with SD3 dictionary, tried everything. It was before, maybe year or even more, that's why I'm not sure, but I'm sure that now I have decompressed version on my reader.

I would need to check if compressed version would be working.

**Comment by Brnoch** [comment]
On my Kobo, new dictionnaries still don't show up after many new versions. Do you have any clue about the problem that prevents the fix to work?

**Comment by kiongping** [comment]
finally figured out. Just have to extract the file, and dump to the dict folder, all done. With my kobo glo hd

**Comment by Frenzie** [comment]
Are you talking about regular extraction (e.g., some .zip or .rar file) or special extraction (i.e., the .dict.dz file)?

**Comment by kiongping** [comment]
just regular one. even with the whole folder is working for me. I put two dictionaries with separate folder in /dict. it just work.

**Comment by kiongping** [comment]
extract the .dz make the dictionary not working in my case.

**Comment by Frenzie** [comment]
It's supposed to be that way. =)

**Comment by Frenzie** [comment]
Well, dunno about not working, lol. But the dictionary takes folders, not
zip files.

**Comment by kiongping** [comment]
yap

**Comment by Brnoch** [comment]
Nice news! Hope I'll get this modification soon. Thanks a lot.

2016-06-25 10:02 GMT+02:00 kiongping <notifications@github.com>:

**Comment by chrox** [comment]
@Frenzie What's preventing this issue being solved? Could you provide a sample StarDict 3.0.0 dictionary and several test cases on this? I believe direct testing on the `sdcv` binary is enough to get the result.

**Comment by Frenzie** [comment]
All works fine. It's the automated releases that don't. Perhaps they don't
pull in the changes from the repo or something?

**Comment by chrox** [comment]
I'm afraid a got the reason:
```
# Not currently on any branch.
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   src/cJSON/.deps/cJSON.Po
#
no changes added to commit (use "git add" and/or "git commit -a")
sdcv $ git log
commit 7f21045094191804149b36a7cea3045bba0770d9
Author: chrox <chrox.huang@gmail.com>
Date:   Wed Apr 15 20:08:58 2015 +0800

    fix android build of sdcv

commit 861a2b8847c5ffc5ea00cf00e4ef39e631e922ef
Author: chrox <chrox.huang@gmail.com>
Date:   Wed Apr 15 20:07:43 2015 +0800

    update config.guess and config.sub

commit 0d3852a42133e45b8842ca9e8343f4f51aa8beec
```

The `sdcv` repo is indeed not updated for some reason on the nightly build machine. Will fix it now. Then tomorrow's nightly build should fix this problem, hopefully.

**Comment by Brnoch** [comment]
Hi,
Unfortunately, I still can't see the modification after upgrading koreader to the latest nightly build.

**Comment by chrox** [comment]
It turns out that we didn't update the `sdcv` in koreader-base at all. See [here](https://github.com/koreader/koreader-base/blob/master/thirdparty/sdcv/CMakeLists.txt#L29-L34):
```
ko_write_gitclone_script(
    GIT_CLONE_SCRIPT_FILENAME
    git://github.com/koreader/sdcv.git
    7f21045094191804149b36a7cea3045bba0770d9
    ${SOURCE_DIR}
)
```

**Comment by Frenzie** [comment]
Ah, so that's the answer to [my question above](https://github.com/koreader/koreader/issues/1994#issuecomment-220014020). But I'm fairly certain that I tested it with `./kodev build` on a freshly pulled repo last month.

**Comment by Brnoch** [comment]
Thanks, it works like a charm now! I appreciate it a lot.
