### ISSUE TITLE
Build Failure on OS X

### ISSUE THREAD

**Issue by Sunkworld** [koreader/koreader#2144]
* KOReader version:
* Device:OS X 10.11.5

#### Issue
Build failed on OS X. Seems something wrong with freetype2?
Here's the log:

Undefined symbols for architecture x86_64:
  "_FT_GetFilePath_From_Mac_ATS_Name", referenced from:
     -exported_symbol[s_list] command line option
  "_FT_GetFile_From_Mac_ATS_Name", referenced from:
     -exported_symbol[s_list] command line option
  "_FT_GetFile_From_Mac_Name", referenced from:
     -exported_symbol[s_list] command line option
  "_FT_New_Face_From_FOND", referenced from:
     -exported_symbol[s_list] command line option
  "_FT_New_Face_From_FSRef", referenced from:
     -exported_symbol[s_list] command line option
  "_FT_New_Face_From_FSSpec", referenced from:
     -exported_symbol[s_list] command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [/Users/Yuuko/Downloads/koreader/base/thirdparty/freetype2/build/x86_64-apple-darwin15.5.0/freetype2-prefix/src/freetype2-build/libfreetype.la] Error 1
make[4]: *** [freetype2-prefix/src/freetype2-stamp/freetype2-build] Error 2
make[3]: *** [CMakeFiles/freetype2.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build/x86_64-apple-darwin15.5.0/libs/libfreetype.6.dylib] Error 2
make: *** [all] Error 2
Failed to build emulator!

**Comment by NiLuJe** [comment]
Woops, thought the Mac buildfix went into the 2.6.4 release, they didn't.

Will bump FT to latets git, that should fix it.

Thanks for the report ;).

**Comment by Sunkworld** [comment]
I update to the latest version, first run './kodev fetch-thirdparty' then './kodev build', but the problem still exists, and the log is just the same...

**Comment by houqp** [comment]
I don't have max os with me any more. You should hunt down @chrox at PekingU and ask for offline "customer sevice" :P

**Comment by Sunkworld** [comment]
😂😂

**Comment by houqp** [comment]
@Sunkworld can you try revert to commit 273a0cb7ee24b9285d0f164737de7f3c5decb66f to see if this error still exist?

**Comment by Sunkworld** [comment]
@houqp I tried to revert to that, and get an error about evernote-sdk-lua; after I manually add the files needed to the specific directory, it turns out that the gui can be opened after, but when I try to open any file, it exited. Besides, it rebuild several dependencies starting from lua-Spore everytime.
Here's the log:
./luajit: frontend/apps/reader/modules/readerdictionary.lua:8: module 'json' not found:
	no field package.preload['json']
	no file 'common/json.lua'
	no file 'rocks/share/lua/5.1/json.lua'
	no file 'frontend/json.lua'
	no file './json.lua'
	no file '/usr/local/share/luajit-2.1.0-beta2/json.lua'
	no file '/usr/local/share/lua/5.1/json.lua'
	no file '/usr/local/share/lua/5.1/json/init.lua'
	no file 'common/json.so'
	no file 'common/json.dll'
	no file '/usr/lib/lua/json.so'
	no file 'rocks/lib/lua/5.1/json.so'
	no file './json.so'
	no file '/usr/local/lib/lua/5.1/json.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	frontend/apps/reader/modules/readerdictionary.lua:8: in main chunk
	[C]: in function 'require'
	frontend/apps/reader/readerui.lua:38: in main chunk
	[C]: in function 'require'
	frontend/apps/filemanager/filemanager.lua:108: in function 'onFileSelect'
	frontend/ui/widget/filechooser.lua:185: in function 'onMenuSelect'
	frontend/ui/widget/menu.lua:735: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:75: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:75: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:75: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'handleEvent'
	frontend/ui/uimanager.lua:389: in function 'sendEvent'
	frontend/ui/uimanager.lua:36: in function '__default__'
	frontend/ui/uimanager.lua:655: in function 'handleInput'
	frontend/ui/uimanager.lua:694: in function 'run'
	./reader.lua:172: in main chunk
	[C]: at 0x0100001010
~/Downloads/koreader

**Comment by houqp** [comment]
lua-Spore is the library that also introduces the luajson module. The emulator is crashing because it can't find the json module. So looks like lua-Spore is not built correctly. Can you run `kodev build -v` and paste the build log for lua-Spore here?

**Comment by Sunkworld** [comment]
@houqp 

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C base
install -d thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0
rm -f /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/lua-Spore-prefix/src/lua-Spore/../lua-Spore-stamp/lua-Spore-build
rm -f build/x86_64-apple-darwin15.5.0/rocks/lib/luarocks/rocks/lua-spore/0.3.1-1/lua-spore-0.3.1-1.rockspec
cd thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0 && \
		cmake -DOUTPUT_DIR="/Users/Yuuko/Downloads/koreader/base/build/x86_64-apple-darwin15.5.0" \
		-DLUA_SPORE_VER=lua-spore-0.3.1-1 -DLD="gcc" \
		-DCC="gcc" -DCFLAGS="-O2 -ffast-math -pipe -fomit-frame-pointer  -march=native -fPIC -I/Users/Yuuko/Downloads/koreader/base/thirdparty/luajit/build/x86_64-apple-darwin15.5.0/luajit-prefix/src/luajit/src" \
		-DLUA_INCDIR="/Users/Yuuko/Downloads/koreader/base/thirdparty/luajit/build/x86_64-apple-darwin15.5.0/luajit-prefix/src/luajit/src" -DLUA_LIBDIR="/Users/Yuuko/Downloads/koreader/base/build/x86_64-apple-darwin15.5.0/libs/" \
		 \
		/Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore && \
		/Applications/Xcode.app/Contents/Developer/usr/bin/make
Re-run cmake no build system arguments
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0
/usr/local/Cellar/cmake/3.6.0/bin/cmake -H/Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore -B/Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0 --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.6.0/bin/cmake -E cmake_progress_start /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/CMakeFiles /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/lua-Spore.dir/build.make CMakeFiles/lua-Spore.dir/depend
cd /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0 && /usr/local/Cellar/cmake/3.6.0/bin/cmake -E cmake_depends "Unix Makefiles" /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0 /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0 /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/CMakeFiles/lua-Spore.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/lua-Spore.dir/build.make CMakeFiles/lua-Spore.dir/build
[ 12%] Performing build step for 'lua-Spore'
cd /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/lua-Spore-prefix/src/lua-Spore && sh -c "luarocks make --tree=/Users/Yuuko/Downloads/koreader/base/build/x86_64-apple-darwin15.5.0/rocks rockspec/lua-spore-0.3.1-1.rockspec CC=\"gcc\" CFLAGS=\"-O2 -ffast-math -pipe -fomit-frame-pointer  -march=native -fPIC -I/Users/Yuuko/Downloads/koreader/base/thirdparty/luajit/build/x86_64-apple-darwin15.5.0/luajit-prefix/src/luajit/src\" LD=\"gcc\" LUA_INCDIR=\"/Users/Yuuko/Downloads/koreader/base/thirdparty/luajit/build/x86_64-apple-darwin15.5.0/luajit-prefix/src/luajit/src\" LUA_LIBDIR=\"/Users/Yuuko/Downloads/koreader/base/build/x86_64-apple-darwin15.5.0/libs/\""
Updating manifest for /Users/Yuuko/Downloads/koreader/base/build/x86_64-apple-darwin15.5.0/rocks/lib/luarocks/rocks-5.2
lua-spore 0.3.1-1 is now built and installed in /Users/Yuuko/Downloads/koreader/base/build/x86_64-apple-darwin15.5.0/rocks (license: MIT/X11)

cd /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/lua-Spore-prefix/src/lua-Spore && /usr/local/Cellar/cmake/3.6.0/bin/cmake -E touch /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/lua-Spore-prefix/src/lua-Spore-stamp/lua-Spore-build
[ 25%] No install step for 'lua-Spore'
cd /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/lua-Spore-prefix/src/lua-Spore && /usr/local/Cellar/cmake/3.6.0/bin/cmake -E echo_append
cd /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/lua-Spore-prefix/src/lua-Spore && /usr/local/Cellar/cmake/3.6.0/bin/cmake -E touch /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/lua-Spore-prefix/src/lua-Spore-stamp/lua-Spore-install
[ 37%] Completed 'lua-Spore'
/usr/local/Cellar/cmake/3.6.0/bin/cmake -E make_directory /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/CMakeFiles
/usr/local/Cellar/cmake/3.6.0/bin/cmake -E touch /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/CMakeFiles/lua-Spore-complete
/usr/local/Cellar/cmake/3.6.0/bin/cmake -E touch /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/lua-Spore-prefix/src/lua-Spore-stamp/lua-Spore-done
[100%] Built target lua-Spore
/usr/local/Cellar/cmake/3.6.0/bin/cmake -E cmake_progress_start /Users/Yuuko/Downloads/koreader/base/thirdparty/lua-Spore/build/x86_64-apple-darwin15.5.0/CMakeFiles 0
# set up some needed paths and links
install -d build/x86_64-apple-darwin15.5.0/{cache,history,clipboard,fonts} /Users/Yuuko/Downloads/koreader/base/build/x86_64-apple-darwin15.5.0/plugins/evernote.koplugin/thrift
ln -sf /Users/Yuuko/Downloads/koreader/base/thirdparty/kpvcrlib/cr3.css build/x86_64-apple-darwin15.5.0/data/
# setup Evernote SDK
cd /Users/Yuuko/Downloads/koreader/base/thirdparty/evernote-sdk-lua/build/x86_64-apple-darwin15.5.0/evernote-sdk-lua-prefix/src/evernote-sdk-lua && \
		cp -R *.lua evernote /Users/Yuuko/Downloads/koreader/base/build/x86_64-apple-darwin15.5.0/plugins/evernote.koplugin && \
		cp thrift/*.lua /Users/Yuuko/Downloads/koreader/base/build/x86_64-apple-darwin15.5.0/plugins/evernote.koplugin/thrift
test -e build/x86_64-apple-darwin15.5.0/rocks/share/lua/5.1/re.lua && chmod 664 build/x86_64-apple-darwin15.5.0/rocks/share/lua/5.1/re.lua || true  # hot fix re.lua permission
install -d koreader-emulator-x86_64-apple-darwin15.5.0/koreader
rm -f koreader-emulator-x86_64-apple-darwin15.5.0/koreader/git-rev; echo v2015.11-515-g9364ff5 > koreader-emulator-x86_64-apple-darwin15.5.0/koreader/git-rev
cp -f base/ev_replay.py koreader-emulator-x86_64-apple-darwin15.5.0/koreader/
[*] create symlink instead of copying files in development mode
cd koreader-emulator-x86_64-apple-darwin15.5.0/koreader && \
		ln -sf ../../base/build/x86_64-apple-darwin15.5.0/* .
[*] install front spec only for the emulator
cd koreader-emulator-x86_64-apple-darwin15.5.0/koreader/spec && test -e front || \
		ln -sf ../../../../spec ./front
cd koreader-emulator-x86_64-apple-darwin15.5.0/koreader/spec/front/unit && test -e data || \
		ln -sf ../../test ./data
for f in reader.lua frontend resources defaults.lua datastorage.lua l10n utils README.md COPYING; do \
		ln -sf ../../$f koreader-emulator-x86_64-apple-darwin15.5.0/koreader/; \
	done
[*] Install plugins
cp -R plugins/* koreader-emulator-x86_64-apple-darwin15.5.0/koreader/plugins/
[*] Installresources
cp -R -pL resources/fonts/* koreader-emulator-x86_64-apple-darwin15.5.0/koreader/fonts/
install -d koreader-emulator-x86_64-apple-darwin15.5.0/koreader/{screenshots,data/{dict,tessdata},fonts/host,ota}

**Comment by houqp** [comment]
Weird, there is no error in the build. Can you confirm that `build/x86_64-apple-darwin15.5.0/rocks/lib/luarocks/rocks/lua-spore/0.3.1-1/lua-spore-0.3.1-1.rockspec` does not exist after the build is done?

**Comment by Sunkworld** [comment]
@houqp actually there is a one as `build/x86_64-apple-darwin15.5.0/rocks/lib/luarocks/rocks-5.2/lua-spore/0.3.1-1/lua-spore-0.3.1-1.rockspec`

**Comment by houqp** [comment]
what's in `build/x86_64-apple-darwin15.5.0/rocks/share/lua/5.1/`? Is there a `json.lua` file?

**Comment by Sunkworld** [comment]
yes, there is, though the version is 5.2, and there are other files/folders "Spore", "Spore.lua", "json", "re.lua".

**Comment by chrox** [comment]
Did you try deleting the whole `base/thirdparty/lua-Spore/build` directory and starting over again? And you may need a VPN in order to download some GFWed contents in the building process if you are in mainland China.

**Comment by Sunkworld** [comment]
@chrox I tried that and it still doesn't work. As for vpn, I have vps+shadowsocks, but I'm not sure whether the download would go through it.

**Comment by houqp** [comment]
I think luajit only works with 5.1. Do you have a local 5.2 lua installation?

**Comment by Sunkworld** [comment]
@houqp I manually install lua 5.1.5, delete the folder, and rebuild, but still a folder named 5.2 reappears.

**Comment by houqp** [comment]
Just to confirm `5.2` is the root cause, could you try rename it manually to `5.1` and see if it helps? From the crash log, it is searching the module from `5.1` directory: 

```
no file 'rocks/lib/lua/5.1/json.so'
no file './json.so'
no file '/usr/local/lib/lua/5.1/json.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by houqp** [comment]
lua-spore is built with luarocks, how did you install luarocks in your mac?

**Comment by Sunkworld** [comment]
@houqp renaming does not work, and the version of lua displayed when running `luarocks --help` is 5.2, how should I fix it?

**Comment by houqp** [comment]
How did you install the current luarocks in the first place? You should try remove it then install one that's compiled for 5.1.

I usually install it manually to my home directory, see: https://github.com/koreader/koreader/blob/master/.ci/install.sh#L10

I set the `-DCMAKE_INSTALL_PREFIX` to `$HOME/.local`. Then make sure `$HOME/.local/bin` is added to your path.

**Comment by houqp** [comment]
Alternatively, you can try: https://github.com/DhavalKapil/luaver

**Comment by chrox** [comment]
Yeah, when I was porting Koreader to Mac OSX, I had installed Torch7 and been in the torch environment which has luarocks-5.1 installed. Thus koreader was built with luarocks-5.1. I think this the reason as when `brew install luarocks` it installs luarocks-5.2.

**Comment by Sunkworld** [comment]
it seems to work when I manually install luarocks-5.1 and redownload koreader...

**Comment by houqp** [comment]
I don't think you will need to redownload koreader though. Calling `./kodev clean` should be enough. Now that the rocks issue is fixed, can you confirm that you are still having the freetype build issue with the latest master?

**Comment by Sunkworld** [comment]
indeed, I redownload the latest one and it works...

**Comment by houqp** [comment]
nice! i am going to mark this issue as close then :)

**Comment by chrox** [comment]
And we need to update the README.md for the luarocks-5.1 as one of the prerequisites.

**Comment by houqp** [comment]
Do you think it makes for us to build our own luarocks so people don't have to mess with the system one. Looks like it's very easy to create a self contained luarocks that's compiled against our own `luajit`.

**Comment by chrox** [comment]
That will be great. :+1:

**Comment by NiLuJe** [comment]
Yeah, it's always been a bit of a PITA, that'd save a lot of potential
trouble ;).
