### ISSUE TITLE
Swiping down exits to OS instead of opening the Menu.

### ISSUE THREAD

**Issue by camifran** [koreader/koreader#2790]
* KOReader version: 2015110994
* Device: Kindle Voyage

#### Issue

Swiping down exits to OS instead of opening the Menu.

#### Steps to reproduce

Update to the last version over developper OTA channel.
Try to open the menu inside the book or directly from the file manager.
You've exited to the Kindle OS.

I've since rolled back to 2015110894 and everything works by tapping the menu.

**Comment by Frenzie** [comment]
Is there a way to get error logs from the Kindle? All's been working fine on the emulator and on my Kobo H2O. Actually since nothing changed about the actual menu display I would only expect any issues as to whether the menu shows up at all, not a crash.

**Comment by Eduardomb22** [comment]
Works fine at kindle ppw3

**Comment by SwissNeptun** [comment]
Same issue on Kobo Aura H2O

**Comment by camifran** [comment]
I don't know how to get a log? Is there an option for it?

**Comment by allati** [comment]
[crash.txt](https://github.com/koreader/koreader/files/938604/crash.txt)
Crash log from my Aura H2O. The device is not Voyage, but the problem may be the same since symptoms match. I resolved the issue by removing storage plugin.

**Comment by Frenzie** [comment]
@camifran Is it possible that deleting the plugins/storage.plugin directory would work for you?

@allati Thank you. Did you update manually?

**Comment by allati** [comment]
I have updated OTA, then the crashing started. Updated manually afterwards and finally removed plugin.

**Comment by houqp** [comment]
Sorry for the trouble. It's unacceptable to have plugins break the reader like this. Given it's not the first time this happen. I am going to add some save guard code now. I will also look into improving the OTA process, I believe currently it won't delete unused files, which is what's causing the crash for you right now :(

**Comment by Frenzie** [comment]
@houqp Indeed, it's not deleted even though I mistakenly thought it was. For me it's "just" not crashing.

**Comment by Frenzie** [comment]
Fixed by #2795.

**Comment by camifran** [comment]
I updated to the latest OTA version (again; v2015.11-995.gd6c81f5) and it's still crashing.
I deleted the storagestat.koplugin directory fro te plugins directory since I do not have a storage.plugin directory there, and then the menu appeared and did not crash. 

Will it be fixed in the next nightly?

Thank you!

**Comment by Frenzie** [comment]
It should be! 955 predates the fix.

**Comment by camifran** [comment]
But I updated to 995, not 955?

**Comment by Frenzie** [comment]
Gah, I shouldn't reply on my phone I guess. d6c81f5 (995) is from a couple of days ago. The fix is from just last night.
