### ISSUE TITLE
Frontlight does not turn off but dims to minimum intensity (sleep and awake)

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2973]
* KOReader version: v2015.11-1062-gb680a3f
* Device: Kobo Glo HD

#### Issue
The frontlight is not turned off when entering sleep mode. Instead it dims to minimum intensity which is only noticeable in dimly lit conditions.
Edit: This also happens when toggling the light off during reading.

This issue appeared in `v2015.11-1059-g63f2284`.
I was unable to test `v2015.11-1058-g53eb4de` as this version crashes immediately.
The last correctly working version is `v2015.11-1057-ged0ba67`

#### Steps to reproduce
1. Turn on frontlight
2. Sleep the device

**Comment by agaAdams** [comment]
- Device: KA1
- KOReader version: from v2015.11-1058 on, including 1064

Same issue here. Additionally I can't turn off the frontlight in KOReader at all. Toggling 'light off' reduces it to minimum intensity, but never turns it off.

**Comment by a-kohout** [comment]
Pinging @Hzj-jie

**Comment by Hzj-jie** [comment]
This should be fixed by https://github.com/koreader/koreader/commit/b5c77af15caf07012e6cee768d77ecb3a74505cd and https://github.com/koreader/koreader/commit/05769872c717d1e6dc41f5d83d4c59ac92bfd766

**Comment by cramoisi** [comment]
Got this bug, bother me so I revert back to the old nightly (may 17, 2017) and still have the incorrect illumination. Erase default.persistant and setting.reader... no effect.
Any idea ?

**Comment by a-kohout** [comment]
I can confirm that this is fixed in `v2015.11-1068-gc8be274`
