### ISSUE TITLE
Android still crash with 1054-g6870bc2.apk

### ISSUE THREAD

**Issue by skygragon** [koreader/koreader#3112]
same 'not able to load libs/libmupdf.so' error as #2853.

Both failed on my two android devices:
1. Boox EInk reader: android 4.0
2. Redmi Note 4 phone: android 6.0

same error since 1023-g773e24f.apk. While 894-gd168db9.apk has no such issue.

**Comment by skygragon** [comment]
I also tried to "upgrade" from 894-gd168db9 to 1054-g6870bc2, but it reported mismatch signature thus I have to uninstall 894 first then install 1054. Seems the newest release is signed with different key?

**Comment by Frenzie** [comment]
In 1023-g773e24f that's to be expected as it predates the fix. Are you sure it's the same libmupdf issue?

Unfortunately I just noticed that https://github.com/koreader/koreader/compare/16dd517...1f75bc6 seems to result in a crash on my Xperia Ray. The LuaJIT bump is the only thing I see on there, which is #!@@#$.

**Comment by skygragon** [comment]
With 1054-g6870bc2 it shows following logs:

```
I/luajit-launcher( 5067): Change directory to /data/data/org.koreader.launcher/files
I/KOReader( 5067): intent file path
I/imx6.gralloc( 1987): Display Request: 3544 (0, 0) - (1600, 1200)  mode = 0x5 flags = 0x0
V/threaded_app( 5067): WindowFocusChanged: 0x1de3e10 -- 1
I/KOReader( 5067): run command chmod 755 ./sdcv
I/KOReader( 5067): command stdout:
I/KOReader( 5067): command stderr:
I/KOReader( 5067): command res:0
I/KOReader( 5067): run command chmod 755 ./tar
I/KOReader( 5067): command stdout:
I/KOReader( 5067): command stderr:
I/KOReader( 5067): command res:0
I/KOReader( 5067): run command chmod 755 ./zsync
I/KOReader( 5067): command stdout:
I/KOReader( 5067): command stderr:
I/KOReader( 5067): command res:0
I/KOReader( 5067): try to load module libs/libkoreader-lfs.so
I/KOReader( 5067): external storage /mnt/sdcard
I/KOReader( 5067): ffi.load SDL2
I/KOReader( 5067): ffi.load SDL
I/ActivityManager( 2109): Process com.onyx.kreader (pid 3550) has died.
I/imx6.gralloc( 1987): Display Request: 3545 (0, 0) - (1600, 1200)  mode = 0x5 flags = 0x0
I/KOReader( 5067): INFO  initializing for device Android
I/KOReader( 5067): INFO  framebuffer resolution: {
I/KOReader( 5067):     ["h"] = 1525,
I/KOReader( 5067):     ["w"] = 1200
I/KOReader( 5067): }
I/KOReader( 5067): ffi.load libs/libmupdf.so
E/luajit-launcher( 5067): Failed to run script: setupkoenv.lua:27: Not able to load dynamic library: libs/libmupdf.so
V/threaded_app( 5067): android_app_destroy!
```

But it's weird that /data/data/org.koreader.launcher/files/libs/libmupdf.so does exist, is there any way to manually fix this search/load behavior?

**Comment by Frenzie** [comment]
The relevant change in the source is https://github.com/koreader/android-luajit-launcher/commit/c139b545f96dec894eb2dc6fe6cb37c03bc8d0ca except that's already included.

For me it simply does this:

```
08-21 10:36:34.742 14021 14034 I KOReader: INFO  initializing for device Android
08-21 10:36:34.742 14021 14034 I KOReader: INFO  framebuffer resolution: {
08-21 10:36:34.742 14021 14034 I KOReader:     ["h"] = 854,
08-21 10:36:34.742 14021 14034 I KOReader:     ["w"] = 480
08-21 10:36:34.742 14021 14034 I KOReader: }
08-21 10:36:34.775 14021 14034 I KOReader: ffi.load libs/libmupdf.so
08-21 10:36:34.837 14021 14034 W linker  : /data/data/org.koreader.launcher/files/libs/libmupdf.so: unused DT entry: type 0xf arg 0x835e
08-21 10:36:34.842 14021 14034 I KOReader: ffi.load libs/libwrap-mupdf.so
08-21 10:36:34.882 14021 14034 W linker  : /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so: unused DT entry: type 0xf arg 0x8d8
08-21 10:36:34.882 14021 14034 W linker  : /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so: is missing DT_SONAME will use basename as a replacement: "libwrap-mupdf.so"
08-21 10:36:34.901 14021 14034 I KOReader: ffi.load libs/libfreetype.so.6
08-21 10:36:34.944 14021 14034 I KOReader: try to load module common/serialize.so
```

Could you double-check slightly higher in the log whether you definitely have the right version? The one I just pulled this log from confirms it's 16dd517 from 10 days ago.

```
08-21 10:36:33.293 14021 14034 I luajit-launcher: Check file in asset module: koreader-g16dd517.7z
08-21 10:36:33.294 14021 14034 I luajit-launcher: Skip installation for revision g16dd517
```

**Comment by skygragon** [comment]
```
I/luajit-launcher( 5067): Check file in asset module: koreader-g6870bc2.7z
I/luajit-launcher( 5067): Found new package revision g6870bc2
V/threaded_app( 5067): WindowFocusChanged: 0x1de3e10 -- 0
I/luajit-launcher( 5067): Installing new koreader package to /data/data/org.koreader.launcher/files
I/luajit-launcher( 5067): ffi.load liblzma.so
D/dalvikvm( 5067): GC_CONCURRENT freed 363K, 4% free 10405K/10823K, paused 1ms+3ms
I/luajit-launcher( 5067): dismiss progress dialog
I/luajit-launcher( 5067): Change directory to /data/data/org.koreader.launcher/files
```

**Comment by Frenzie** [comment]
Yeah, that's the right one. :/

**Comment by Frenzie** [comment]
This doesn't help you, but I fixed the Android issue I noticed in #3114, meaning v2015.11-1152-gabaa699 and up will be fine again. You can grab that build [here](http://build.koreader.rocks/download/nightly/v2015.11-1152-gabaa699/). I've also attached it to this message, but you'd have to remove the .zip at the end.

[koreader-android-arm-linux-androideabi-v2015.11-1152-gabaa699.apk.zip](https://github.com/koreader/koreader/files/1239191/koreader-android-arm-linux-androideabi-v2015.11-1152-gabaa699.apk.zip)

I'm assuming it won't make a difference, but I guess it's worth a try. Irreproducible errors are the worst. >_<

**Comment by skygragon** [comment]
Thanks @Frenzie , but unfortunately the same error still occurs...

**Comment by chenxingqun** [comment]
My Boox Max Carta with android 4.04 crashes too.

**Comment by skygragon** [comment]
I tried to modify setupkoenv.lua file to load libmupdf.so since I notice that library is always there (/data/data/org.koreader.launcher/files/libs/libmupdf.so) while somehow lua failed to find it. But I'm not a luajit guy and other libraries kept failing even after libmupdf.so is loaded ...

**Comment by Frenzie** [comment]
What change did you try exactly?

**Comment by skygragon** [comment]
@Frenzie Amazing work! My problem goes away with this fix!

**Comment by Frenzie** [comment]
You're welcome. :-)
