### ISSUE TITLE
Development & debugging on Android - howto

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3385]
As there's a lot of problems around development & debugging on Android 
 `+` recently it has changed (we've Koreader for x86 arch) 
 `+` a lot of information is split between issues 
and we miss one place to sum up the knowledge that everyone might not be aware.

`-` I created initial version of HowTo :
https://github.com/koreader/koreader/wiki/Development-and-Debugging-on-Android

Please help writing it so new developers wouldn't have to reinvent the wheel.

**Comment by Frenzie** [comment]
Btw, apps like ZeroBrane can be used to debug the Lua part (although I haven't really felt the need to). I'm not sure if that is possible on Android at all though.

https://studio.zerobrane.com/doc-luajit-debugging

**Comment by Frenzie** [comment]
strace https://forum.xda-developers.com/showthread.php?t=2516002

Haven't tried it, but basic tools like that are an obvious necessity.

Android itself also has some incomprehensible gibberish about it: https://source.android.com/devices/tech/debug/strace

It sounds fine — execute some useful commands in the shell more or less like you would on a proper Linux — but my phone has none of those commands.

The emulator does have them, but that's useless. Things are already working just fine on the emulator.

**Comment by pazos** [comment]
ndk-gdb works fine for debugging luajit-launcher.

```gdb
ndk-gdb --launch 
Redirecting gdbserver output to /tmp/gdbclient.log
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
warning: .dynamic section for "/home/pazos/escritorio/koreader/platform/android/luajit-launcher/obj/local/armeabi-v7a/liblzma.so" is not at the expected address (wrong library or version mismatch?)
warning: Could not load shared library symbols for 188 libraries, e.g. /system/lib/libcutils.so.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
0xa6a724d4 in syscall ()
   from /home/pazos/escritorio/koreader/platform/android/luajit-launcher/obj/local/armeabi-v7a/system/lib/libc.so
(gdb) continue
Continuing.
warning: Could not load shared library symbols for /data/app/org.koreader.launcher-1/oat/arm/base.odex.
Do you need "set solib-search-path" or "set sysroot"?
[New Thread 3893.3952]
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/libs/libblitbuffer.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/libs/libfreetype.so.6.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/libs/libluacompat52.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/common/serialize.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/rocks/lib/lua/5.1/lpeg.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/common/socket/score.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/common/mime/mcore.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/libs/libcrypto.so.1.0.0.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/libs/libssl.so.1.0.0.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/common/ssl.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/libs/libz.so.1.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/libs/libjpeg.so.8.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/libs/libmupdf.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so.
Do you need "set solib-search-path" or "set sysroot"?
```

This is only useful if you want to debug an early crash on the loader.

**Comment by Frenzie** [comment]
What folder are you running this ndk-gdb from? Does it work on non-root?

**Comment by pazos** [comment]
from platform/android/luajit-launcher. Yes it should work on any device. On Ko default ndk (15?) I needed to change the python wrapper yo be able to detect manifest api.

**Comment by Frenzie** [comment]
That script won't run right for me. Do I need to add something to $PATH?

A big list of errors like this:
```
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/home/frans/src/kobo/koreader/base/toolchain/android-ndk-r15c/prebuilt/linux-x86_64/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/frans/src/kobo/koreader/base/toolchain/android-ndk-r15c/prebuilt/linux-x86_64/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/frans/src/kobo/koreader/base/toolchain/android-ndk-r15c/prebuilt/linux-x86_64/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/frans/src/kobo/koreader/base/toolchain/android-ndk-r15c/prebuilt/linux-x86_64/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/frans/src/kobo/koreader/base/toolchain/android-ndk-r15c/prebuilt/linux-x86_64/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/frans/src/kobo/koreader/base/toolchain/android-ndk-r15c/prebuilt/linux-x86_64/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
```

Also how did you change the Python wrapper?

**Comment by pazos** [comment]
export PATH=$PATH:whatever/android-ndk-r15c/prebuilt/linux-x86_64/bin

Original error was 
```
/mnt/compartido/android/android-ndk-r15c-orig/build/gmsl/__gmsl:512: *** non-numeric second argument to `wordlist' function: ''.  Stop.
ERROR: Failed to retrieve application ABI from Android.mk.
```
Fixed (with google's help):

```diff
--- android-ndk-r15c-orig/build/gmsl/__gmsl     2017-07-21 11:03:50.000000000 +0200
+++ android-ndk-r15c/build/gmsl/__gmsl  2019-01-10 21:20:16.847568638 +0100
@@ -509,7 +509,7 @@
 # Arguments: 1: A number in human-readable integer form
 # Returns:   Returns the integer encoded as a string of x's
 # ----------------------------------------------------------------------------
-int_encode = $(__gmsl_tr1)$(wordlist 1,$1,$(__gmsl_input_int))
+int_encode = $(__gmsl_tr1)$(wordlist 1,$(words $1),$(__gmsl_input_int))
 
 # The arithmetic library functions come in two forms: one form of each
 # function takes integers as arguments and the other form takes the
```

**Comment by Frenzie** [comment]
> export PATH=$PATH:whatever/android-ndk-r15c/prebuilt/linux-x86_64/bin

That doesn't resolve the errors mentioned above for me.

> Fixed (with google's help):

That does help, at least a little.

```
Redirecting gdbserver output to /tmp/gdbclient.log
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
warning: Could not load shared library symbols for 100 libraries, e.g. /system/lib/libcutils.so.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
0xffffe430 in __kernel_vsyscall ()
(gdb) 
```

Using gdbserver on Kobo is super simple, but I can't seem to wrap my head around Android. :blush: 

Anyway, hopefully due to the various errors on my PC, all my phone says is this:

![screenshot_20190110-220046](https://user-images.githubusercontent.com/202757/50996844-5d029600-1523-11e9-9646-80d7f2e709ca.png)

**Comment by pazos** [comment]
yep, I get this screen too. This is because we're running with `--launch` because we want to debug early stuff. You only need to type `continue` and the program will start.

The other option is start KOReader first and just use `--attach` but you'll lose some loader info.

Anyways this is only for the launcher and can be useful to debug some commands that runs on the UiThread. For the most part luajit-launcher will provide its own useful messages on android log.

**Comment by pazos** [comment]
Once the program continues you can use `Ctrl+C` to interrupt it on demand. You'll see

```gdb
Thread 1 "reader.launcher" received signal SIGINT, Interrupt.
0xa6aa3348 in __epoll_pwait ()
```
Which is the android ALooper_pollAll handled from lua.

Once you finish checking the current state (since the app will freeze when ALooper_pollAll is interrupted) you can type `continue` again.

**Comment by Frenzie** [comment]
It's not doing too much I'm afraid. I already tried continue to little success, I should've probably mentioned I already tried that. :-)

![20190110_223003](https://user-images.githubusercontent.com/202757/50998389-83c2cb80-1527-11e9-9b70-5626048a7ea3.jpg)

**Comment by Frenzie** [comment]
Well, it seems to have worked out in the end after some extra manual killing.

```
Thread 1 "reader.launcher" received signal SIGINT, Interrupt.
0xffffe430 in __kernel_vsyscall ()
(gdb) bt
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7283735 in syscall ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf730030c in pthread_cond_wait ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#3  0xf2060a82 in ?? ()
#4  0xf206002c in ?? ()
#5  0xf752a2ac in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

I'm not really sure if I can do anything with this tbh. It's not really like anything else I've experienced in gdb. But thanks a lot for pointing out how to get something with a semblance of usefulness out of Android. :-)

**Comment by pazos** [comment]
its seems stuck waiting for kernel response to some syscall, but I really don't know. `info threads` may help.

**Android Sucks** :tm:

**Comment by Frenzie** [comment]
Here's the output from that.
```
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 17847.17847 "reader.launcher" 0xffffe430 in __kernel_vsyscall ()
  2    Thread 17847.17852 "Heap thread poo" 0xffffe430 in __kernel_vsyscall ()
  3    Thread 17847.17853 "Signal Catcher" 0xffffe430 in __kernel_vsyscall ()
  4    Thread 17847.17854 "JDWP" 0xffffe430 in __kernel_vsyscall ()
  5    Thread 17847.17855 "ReferenceQueueD" 0xffffe430 in __kernel_vsyscall ()
  6    Thread 17847.17856 "FinalizerDaemon" 0xffffe430 in __kernel_vsyscall ()
  7    Thread 17847.17857 "FinalizerWatchd" 0xffffe430 in __kernel_vsyscall ()
  8    Thread 17847.17858 "HeapTaskDaemon" 0xffffe430 in __kernel_vsyscall ()
  9    Thread 17847.17859 "Binder_1" 0xffffe430 in __kernel_vsyscall ()
  10   Thread 17847.17860 "Binder_2" 0xffffe430 in __kernel_vsyscall ()
  11   Thread 17847.17862 "Binder_3" 0xffffe430 in __kernel_vsyscall ()
  12   Thread 17847.17863 ".ProcessManager" 0xffffe430 in __kernel_vsyscall ()
  13   Thread 17847.17866 "Binder_4" 0xffffe430 in __kernel_vsyscall ()
  14   Thread 17847.17873 "Thread-24156" 0xffffe430 in __kernel_vsyscall ()
  15   Thread 17847.17904 "Binder_5" 0xffffe430 in __kernel_vsyscall ()
```

```
(gdb) thread apply all bt

Thread 15 (Thread 17847.17904):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7303639 in __ioctl ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf7315b4c in ioctl ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#3  0xf768a5b4 in ?? ()
#4  0xeabe0c00 in ?? ()

Thread 14 (Thread 17847.17873):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7303788 in __pselect6 ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf72a2b14 in select ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#3  0xeecd4ce5 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 13 (Thread 17847.17866):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7303639 in __ioctl ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf7315b4c in ioctl ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#3  0xf768a5b4 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 12 (Thread 17847.17863):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7283735 in syscall ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf32a1cef in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 11 (Thread 17847.17862):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7303639 in __ioctl ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf7315b4c in ioctl ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#3  0xf768a5b4 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 10 (Thread 17847.17860):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7303639 in __ioctl ()
---Type <return> to continue, or q <return> to quit---
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf7315b4c in ioctl ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#3  0xf768a5b4 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 9 (Thread 17847.17859):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7303639 in __ioctl ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf7315b4c in ioctl ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#3  0xf768a5b4 in ?? ()
#4  0xeabe0500 in ?? ()

Thread 8 (Thread 17847.17858):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7283735 in syscall ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf32a1cef in ?? ()
#3  0x00000000 in ?? ()

Thread 7 (Thread 17847.17857):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7283735 in syscall ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf32a0e01 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 6 (Thread 17847.17856):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7283735 in syscall ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf32a1cef in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 5 (Thread 17847.17855):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7283735 in syscall ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf32a1cef in ?? ()
#3  0x00000000 in ?? ()

Thread 4 (Thread 17847.17854):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7304d56 in recvmsg ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
---Type <return> to continue, or q <return> to quit---
#2  0xf37c972d in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 3 (Thread 17847.17853):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf730392e in __rt_sigtimedwait ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf72a4950 in sigwait ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#3  0xf36754cc in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 2 (Thread 17847.17852):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7283735 in syscall ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf32a1cef in ?? ()
#3  0x00000000 in ?? ()

Thread 1 (Thread 17847.17847):
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf7283735 in syscall ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#2  0xf730030c in pthread_cond_wait ()
   from /home/frans/src/kobo/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
#3  0xf2160a82 in ?? ()
#4  0xf216002c in ?? ()
#5  0xf752a2ac in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by pazos** [comment]
`Heap thread poo` :laughing: 

Here is a normal output:

```
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 2343.2343 "reader.launcher" 0xb73041e2 in syscall ()
   from /home/pazos/escritorio/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
  2    Thread 2343.2348 "Signal Catcher" 0xb737124b in __rt_sigtimedwait ()
   from /home/pazos/escritorio/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
  3    Thread 2343.2349 "JDWP" 0xb7372053 in recvmsg ()
   from /home/pazos/escritorio/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
  4    Thread 2343.2350 "ReferenceQueueD" 0xb73041e2 in syscall ()
   from /home/pazos/escritorio/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
  5    Thread 2343.2351 "FinalizerDaemon" 0xb73041e2 in syscall ()
   from /home/pazos/escritorio/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
  6    Thread 2343.2352 "FinalizerWatchd" 0xb73041e2 in syscall ()
   from /home/pazos/escritorio/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
  7    Thread 2343.2353 "HeapTaskDaemon" 0xb73041e2 in syscall ()
   from /home/pazos/escritorio/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
  8    Thread 2343.2354 "Binder_1" 0xb7371766 in __ioctl ()
   from /home/pazos/escritorio/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
  9    Thread 2343.2355 "Binder_2" 0xb7371766 in __ioctl ()
   from /home/pazos/escritorio/koreader/platform/android/luajit-launcher/obj/local/x86/system/lib/libc.so
```

I'm not sure if that matters but I'm using the full ndk. I think that KO removes some junk. Am I wrong?

**Comment by Frenzie** [comment]
Closing now since the wiki has the basics covered.
