### ISSUE TITLE
Wifi status not updated, cannot disable wifi on kindle

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#4472]
* KOReader version: v2018.12
* Device: Kindle Paperwhite 3

#### Issue
It seems network status in the menu is not updated and wifi cannot be disabled.
#### Steps to reproduce
Go to wifi tab on kindle, tap Wi-Fi connection

**Comment by NiLuJe** [comment]
Possibly fixed in 2019.01

**Comment by Galunid** [comment]
It seems to be partially fixed. The button does the required action, but the "tick" next to it, doesn't update. It works fine, after exiting the menu, and entering it again, but doesn't work, after putting kindle to sleep. Other than that, after disabling wifi from KOReader and exiting application, the Amazon GUI doesn't update. I'm not sure, if it's supposed to work that way, considering, than when wifi is enabled from KOReader, the icon updates.

-
OT, OTA update didn't work, it failed at zsync I think it tried to download 2019.01, while the most recent is 2019.01.01?

**Comment by Frenzie** [comment]
That's my fault I'm afraid, though that shouldn't make the OTA update fail.

**Comment by Frenzie** [comment]
I made the stable OTA update point to today's nightly (which is practically exactly the same as yesterday's point release stable) since it was the easiest solution.

**Comment by Galunid** [comment]
So I did some digging and I possibly found a problem
**from frontend/ui/network/manager.lua(NetworkMgr:getWifiMenuTable)**
```lua
if wifi_status then
    NetworkMgr:promptWifiOff(complete_callback)
else
    NetworkMgr:promptWifiOn(complete_callback)
```
The `NetworkMgr:promptWifiOn` method takes the callback and passes it to `self:turnOnWifi`
but turnOnWifi doesn't take any arguments, and thus the callback doesn't get executed
The callback function calls the `touchmenu_instance:updateItems()`, so it's possible that it results in not refreshing the menu. The one interesting thing I've found, is that calling `touchmenu_instance:updateItems()` after `NetworkMgr:promptWifiOn(complete_callback)`/`NetworkMgr:promptWifiOff(complete_callback)`
doesn't result in menu refresh. Could someone point me to the file where I can find this method's implementation?

**Comment by Frenzie** [comment]
That's probably this one:

https://github.com/koreader/koreader/blob/ab09dedf33e3cc18f3cf84530d88a77f8ac90cc6/frontend/ui/widget/menu.lua#L889

**Comment by NiLuJe** [comment]
The callback is completely ignored on Kindle (because we defer to the system).

It iis used properly on platforms where we handle wifi ourselves (c.f., frontend/device/kindle/device.lua vs. frontend/device/kobo/device.lua)

**Comment by NiLuJe** [comment]
As for the menu refresh, that may be a remnant of the old "it used to get closed" and now it doesn't?

Can't recall, and don't have a device on hand right now ;).

**Comment by NiLuJe** [comment]
Also, if you could do a bullet-point recap of what you're seeing with the current version, that would help, as the lack of whitespace in your comments is making it hard to figure out which is which ;).

IIRC, it's quite possible that we do not forcibly kill WiFi on exit on Kindle, and this *may* confuse the system.

**Comment by NiLuJe** [comment]
Okay, yeah, menu stays open, which quite possibly wasn't the case the last time someone played with WiFi on Kindle (which is, err, rare, for obvious reasons).

So, yeah, tweaking frontend/device/kindle/device.lua to handle the callback might actually help, good detective work ;).

**Comment by NiLuJe** [comment]
```diff
diff --git a/frontend/device/kindle/device.lua b/frontend/device/kindle/device.lua
index 40f1093c..45fec777 100644
--- a/frontend/device/kindle/device.lua
+++ b/frontend/device/kindle/device.lua
@@ -79,12 +79,18 @@ local Kindle = Generic:new{
 }

 function Kindle:initNetworkManager(NetworkMgr)
-    NetworkMgr.turnOnWifi = function()
+    NetworkMgr.turnOnWifi = function(complete_callback)
         kindleEnableWifi(1)
+        if complete_callback then
+            complete_callback()
+        end
     end

-    NetworkMgr.turnOffWifi = function()
+    NetworkMgr.turnOffWifi = function(complete_callback)
         kindleEnableWifi(0)
+        if complete_callback then
+            complete_callback()
+        end
     end

     NetworkMgr.isWifiOn = function()
```

**Comment by NiLuJe** [comment]
This might be race-y, though, since we defer the actual work to lipc...

**Comment by Galunid** [comment]
So I got this idea, to call the callback method in `NetworkMgr:promptWifiOn` and `NetworkMgr:promptWifiOff`
```lua
function NetworkMgr:promptWifiOn(complete_callback)
    UIManager:show(ConfirmBox:new{
        text = _("Do you want to turn on Wi-Fi?"),
        ok_text = _("Turn on"),
        ok_callback = function()
            self.wifi_was_on = true
            G_reader_settings:saveSetting("wifi_was_on", true)
            self:turnOnWifi(complete_callback) -- this doesn't take any arguments, so I removed 'complete_callback'
            ffiutil.sleep(1) -- for some reason it didn't work without this delay
            complete_callback() -- and call it in this method
        end,
    })
end
```
This works properly for disabling wifi, however it fails when enabling wifi, crushing the whole app
```stack traceback:
        [C]: in function 'tonumber'
        frontend/device/kindle/device.lua:24: in function 'isWifiUp'
        frontend/device/kindle/device.lua:91: in function 'checked_func'
        frontend/ui/widget/touchmenu.lua:74: in function 'init'
        frontend/ui/widget/widget.lua:48: in function 'new'
        frontend/ui/widget/touchmenu.lua:568: in function 'updateItems'
        frontend/ui/network/manager.lua:134: in function 'complete_callback'
        frontend/ui/network/manager.lua:49: in function 'ok_callback'
        frontend/ui/widget/confirmbox.lua:99: in function 'callback'
        frontend/ui/widget/button.lua:203: in function 'action'
        frontend/ui/uimanager.lua:669: in function '_checkTasks'
        frontend/ui/uimanager.lua:893: in function 'handleInput'
        frontend/ui/uimanager.lua:979: in function 'run'
        ./reader.lua:216: in main chunk
        [C]: at 0x00014684
lipc-wait-event exited normally with status: 0
```

This is how the function that causes the fail looks like.
```lua
local function isWifiUp()
    -- NOTE: Pilfered from Cervantes, c.f., #4380
    --       Possibly simpler and more compatible than the lipc approach ;).
    local file = io.open("/sys/class/net/wlan0/carrier", "rb")
    if not file then return 0 end
    local status = tonumber(file:read("*all")) or 0
    file:close()
    return status
end
```

**Comment by NiLuJe** [comment]
That's because I'm terrible at Lua, no worries ;D.

**Comment by Galunid** [comment]
[crash.log](https://github.com/koreader/koreader/files/2752378/crash.log)
Hopefully, this will provide some insight

**Comment by NiLuJe** [comment]
```diff
diff --git a/frontend/device/kindle/device.lua b/frontend/device/kindle/device.lua
index 40f1093c..0166b449 100644
--- a/frontend/device/kindle/device.lua
+++ b/frontend/device/kindle/device.lua
@@ -17,15 +17,6 @@ local function kindleEnableWifi(toggle)
 end
 
 local function isWifiUp()
-    -- NOTE: Pilfered from Cervantes, c.f., #4380
-    --       Possibly simpler and more compatible than the lipc approach ;).
-    local file = io.open("/sys/class/net/wlan0/carrier", "rb")
-    if not file then return 0 end
-    local status = tonumber(file:read("*all")) or 0
-    file:close()
-    return status
-
-    --[[
     local status = 0
     local haslipc, lipc = pcall(require, "liblipclua")
     local lipc_handle = nil
@@ -35,9 +26,15 @@ local function isWifiUp()
     if lipc_handle then
         status = lipc_handle:get_int_property("com.lab126.wifid", "enable")
         lipc_handle:close()
+    else
+        -- NOTE: Pilfered from Cervantes, c.f., #4380
+        --       Possibly race-y, if we're extremely unlucky and lipc drops WiFi between our open and our read...
+        local file = io.open("/sys/class/net/wlan0/carrier", "rb")
+        if not file then return 0 end
+        status = tonumber(file:read("*all")) or 0
+        file:close()
     end
     return status
-    --]]
 end
 
 --[[
@@ -79,12 +76,24 @@ local Kindle = Generic:new{
 }
 
 function Kindle:initNetworkManager(NetworkMgr)
-    NetworkMgr.turnOnWifi = function()
+    NetworkMgr.turnOnWifi = function(complete_callback)
         kindleEnableWifi(1)
+        -- NOTE: As we defer the actual work to lipc,
+        --       we have no guarantee the WiFi state will have changed by the time kindleEnableWifi returns,
+        --       so, delay the callback a bit...
+        if complete_callback then
+            local UIManager = require("ui/uimanager")
+            UIManager:scheduleIn(5, function() complete_callback() end)
+        end
     end
 
-    NetworkMgr.turnOffWifi = function()
+    NetworkMgr.turnOffWifi = function(complete_callback)
         kindleEnableWifi(0)
+        -- NOTE: Same here...
+        if complete_callback then
+            local UIManager = require("ui/uimanager")
+            UIManager:scheduleIn(2, function() complete_callback() end)
+        end
     end
 
     NetworkMgr.isWifiOn = function()
```

This *possibly* won't crash ;p.

This is fairly awful though, the less terrible approach would simply be to close the menu on Kindle.

@poire-z : Can we close the top menu programmatically?

**Comment by Galunid** [comment]
```git
local status = 0
     local haslipc, lipc = pcall(require, "liblipclua")
     local lipc_handle = nil
@@ -35,9 +26,15 @@ local function isWifiUp()
     if lipc_handle then -- lipc_handle is nil, so it'll never be true, did you mean haslipc?
```

**Comment by NiLuJe** [comment]
That's a diff, not the full code ;).

**Comment by NiLuJe** [comment]
c.f., https://github.com/NiLuJe/koreader/blob/c171c26bb099075dcb0508943225b3a7cba6156d/frontend/device/kindle/device.lua

**Comment by Galunid** [comment]
After applying this fix, it still crashes, with a similar message
```
01/12/19-19:47:52 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
01/12/19-19:47:52 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
01/12/19-19:47:52 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
01/12/19-19:47:52 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
./luajit: frontend/device/kindle/device.lua:86: attempt to call upvalue 'complete_callback' (a table value)
stack traceback:
        frontend/device/kindle/device.lua:86: in function 'action'
        frontend/ui/uimanager.lua:669: in function '_checkTasks'
        frontend/ui/uimanager.lua:893: in function 'handleInput'
        frontend/ui/uimanager.lua:979: in function 'run'
        ./reader.lua:210: in main chunk
        [C]: at 0x00014684
lipc-wait-event exited normally with status: 0
```

**Comment by NiLuJe** [comment]
Yup, still terrible at Lua :D.

Try https://github.com/NiLuJe/koreader/blob/6a67314b6a8d680ba05783ee968d323fc02e4bd1/frontend/device/kindle/device.lua?

**Comment by Galunid** [comment]
```diff
diff --git a/frontend/ui/network/manager.lua b/frontend/ui/network/manager.lua
old mode 100644
new mode 100755
index 4e7e0c43..d69097c3
--- a/frontend/ui/network/manager.lua
+++ b/frontend/ui/network/manager.lua
@@ -44,7 +44,9 @@ function NetworkMgr:promptWifiOn(complete_callback)
         ok_callback = function()
             self.wifi_was_on = true
             G_reader_settings:saveSetting("wifi_was_on", true)
-            self:turnOnWifi(complete_callback)
+            self:turnOnWifi()
+            ffiutil.sleep(1)
+            complete_callback()
         end,
     })
 end
@@ -56,7 +58,9 @@ function NetworkMgr:promptWifiOff(complete_callback)
         ok_callback = function()
             self.wifi_was_on = false
             G_reader_settings:saveSetting("wifi_was_on", false)
-            self:turnOffWifi(complete_callback)
+            self:turnOffWifi()
+           ffiutil.sleep(1)
+            complete_callback()
         end,
     })
 end
```
That's how I got it to work. This + your fix to the `isWifiUp` did the trick

**Comment by NiLuJe** [comment]
This can't go in as-is, as it screws with generic code for a platorm-specific issue ;).

**Comment by NiLuJe** [comment]
I updated my branch to simply close the menu on Kindle, as that's the most elegant way of handling this I can think of.

**Comment by poire-z** [comment]
Not sure what menu you're talking about :)
I added some stuff (including network/manager) in #4189 to keep some menu open.
From what I wrote:

> In both cases, provide the TouchMenu instance as the 1st argument to the callback functions (instead of a refresh_menu_func I added previously) so the callback can do more things, like closing, refreshing, changing menu items text and re-ordering...

There are some examples in this PR, like:
```lua
        hold_callback = function(touchmenu_instance)
            UIManager:show(ConfirmBox:new{
                text = _("Clear location history?"),
                ok_text = _("Clear"),
                ok_callback = function()
                    self.location_stack = {}
                    touchmenu_instance:closeMenu()
                end,
            })
```

**Comment by NiLuJe** [comment]
@poire-z : Yeah, I figured it out, thanks :).

**Comment by NiLuJe** [comment]
Okay, https://github.com/NiLuJe/koreader/commit/a2b020b6d0383e9a0b0639291f07a6302912f4eb appears to work on my end, so, eh, that's good enough for me.

**Comment by NiLuJe** [comment]
Okay, and as for the state of WiFi on exit: that's just a graphical issue.

The system is completely aware of the current state of WiFi, it just rarely refreshes the top-menu bar with the WiFi icon, and we happen to restore a full-screen dump of the state of the screen at the time we started.

So if you start in Airplane mode, and you exit KOReader with WiFi on, we restore an Airplane mode icon, but "underneath", it's very much on.

Nothing much we can do about that.

**Comment by Galunid** [comment]
To be honest, I'm not sure, if it's bugged only on kindle
```lua
function NetworkMgr:turnOnWifi() end
function NetworkMgr:turnOffWifi() end
function NetworkMgr:isWifiOn() end
function NetworkMgr:getNetworkList() end
function NetworkMgr:getCurrentNetwork() end
function NetworkMgr:authenticateNetwork() end
function NetworkMgr:disconnectNetwork() end
function NetworkMgr:obtainIP() end
function NetworkMgr:releaseIP() end
```
So I don't think, any other device implements this callback, so it's possible, that menu is not "refreshed" on any other device.

**Comment by Galunid** [comment]
Actually, you can ignore my previous comment, other devices implement this callback.

**Comment by Galunid** [comment]
I tested NiLuJe's solution and it seems to work pretty well for me too

**Comment by NiLuJe** [comment]
Great, thanks for double-checking, I was afraid having USBNet enabled would have skewed my interpretation ;).

I'll clean this up and merge it Soon(TM), thanks again :).

**Comment by Galunid** [comment]
Great, thanks for fixing it too. I guess we can close this issue now, right?

**Comment by NiLuJe** [comment]
It'll be autoclosed once the fix makes it in, so you can leave it, that serves as a reminder ;).
