### ISSUE TITLE
[bug?] Android OTA updates do not seem to work 

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4599]
* KOReader version: 2019.02.01 stable
* Device: pixel XL and fire tablet 10

#### Issue

I wanted to grab the latest bits for Android so I could get the dictionary working.  When I selected development and asked to update it found version 201902000032 so I click update ..

Get "failed to update Koreader" and even after clicking retry and restarting the app there is no difference...

Normally id just download the apk but it looks like there isn't a new release and I'm not up for compiling it right now

**Comment by Frenzie** [comment]
Fixed by #4598, in fact. ;-)

**Comment by Frenzie** [comment]
Or possibly fixed, anyway. I don't know if the post-zsync part of it works.

To get the dictionary working you can just extract the dictionaries into /sdcard/koreader/data/dict

See https://github.com/koreader/koreader/wiki/Dictionary-support

All "download dictionaries" does is that is has a list of known free dictionaries that it downloads & extracts.

Nightlies are built around 6 AM CET, in this case meaning the latest nightly predates the fix by about ten hours.

**Comment by arooni** [comment]
Vaugely related.  When I ran the update on my Kindle it said "error Koreader failed to update and may not work properly " yet I still see the highlight adjustment feature that was just added

**Comment by Frenzie** [comment]
*Very* vaguely related. Android is quite different from other systems. :-)

I've never seen such a message. Do you have enough disk space available? Pinging @NiLuJe

**Comment by arooni** [comment]
I can open a new issue for it if you'd rather 

I have 2gb free.  Ran into it on the previous ota update and again on this one. 

The only thing I can think of is I modified the footer file to be a 12 hour clock.  But it looks like that change was overwritten sometime and now I'm back to the 24 hour clock

**Comment by Frenzie** [comment]
Yes, please open a new issue. Twice in a row is most peculiar. Did you perhaps open one of the Lua files in a text editor via SSH or some such? Mark a file as read-only?

> The only thing I can think of is I modified the footer file to be a 12 hour clock. But it looks like that change was overwritten sometime and now I'm back to the 24 hour clock

Core files will be overwritten by the OTA update, so modifications like that would not persist. I personally actually use OTA updates for that purpose quite deliberately when I'm testing something on my H2O. But as far as the update knows it's just the old file that's being replaced, nothing out of the ordinary. 

For example, that's why defaults.lua says this:
https://github.com/koreader/koreader/blob/333f8658bb3aeef8e75ce9a744a6dacd73e9c9a9/defaults.lua#L1-L2

**Comment by NiLuJe** [comment]
IIRC, that's the error from the *KUAL* extension on Kindle, and it's exactly what it says on the tin: tar/unzip returned an error code.

**Comment by arooni** [comment]
> Yes, please open a new issue. Twice in a row is most peculiar. Did you perhaps open one of the Lua files in a text editor via SSH or some such? Mark a file as read-only?
> 
> > The only thing I can think of is I modified the footer file to be a 12 hour clock. But it looks like that change was overwritten sometime and now I'm back to the 24 hour clock
> 
> Core files will be overwritten by the OTA update, so modifications like that would not persist. I personally actually use OTA updates for that purpose quite deliberately when I'm testing something on my H2O. But as far as the update knows it's just the old file that's being replaced, nothing out of the ordinary.
> 
> For example, that's why defaults.lua says this:
> [koreader/defaults.lua](https://github.com/koreader/koreader/blob/333f8658bb3aeef8e75ce9a744a6dacd73e9c9a9/defaults.lua#L1-L2)
> 
> Lines 1 to 2 in [333f865](/koreader/koreader/commit/333f8658bb3aeef8e75ce9a744a6dacd73e9c9a9)
> 
>  -- To make configuration changes that persists between (nightly) releases, 
>  -- copy defaults.lua to defaults.persistent.lua and make the changes there.

This is well worth reading; I didn't know that my settings were gone unless I saved that.  

Is that the case for the plugins too?  I just noticed that my wallabag, dropbox, and other settings seem to be overwritten?.

i.e. feed_config.persistent.lua ?

**Comment by Frenzie** [comment]
Not generally, but it's possible that one of the plugins has a bug in that regard. You don't need to know all the ins and outs of the program to write a plugin (which is quite intentional!). But I think it's not terribly strange that OTA updating would replace local changes to the source.

If you haven't had any problems with your feed config file, i assume it's fine. ;-)

> This is well worth reading; I didn't know that my settings were gone unless I saved that.

Everything in `/settings` is safe, as well as `settings.reader.lua`. `defaults.lua` is just a bit of a special half-legacy case.

**Comment by arooni** [comment]
I understand the rationale.  Makes sense.

Upon further investigation the only thing that seemed like it lost track of itself was having to log into evernote again.  I didn't see an evernote config file in /settings/

And... if I have defaults.persistent.lua, will I be able to make changes via the UI and have them written to defaults.persistent.lua, or will changes via the UI only be written to defaults.lua (and subject to being overwritten on OTA dev channel updates)?

**Comment by arooni** [comment]
> Or possibly fixed, anyway. I don't know if the post-zsync part of it works.
> 
> To get the dictionary working you can just extract the dictionaries into /sdcard/koreader/data/dict
> 
> See https://github.com/koreader/koreader/wiki/Dictionary-support
> 
> All "download dictionaries" does is that is has a list of known free dictionaries that it downloads & extracts. The extraction part is where it went off course.
> 
> Nightlies are built around 6 AM CET, in this case meaning the latest nightly predates the fix by about ten hours.

What a catch 22 :)

I actually don't see where the koreader directory is supposed to be located on Android.  I'm sure it's installed but doesn't seem listed in /sdcard/koreader

**Comment by Frenzie** [comment]
> Upon further investigation the only thing that seemed like it lost track of itself was having to log into evernote again (that and the whipsersync position syncing). I didn't see an evernote config file in /settings/ ... Did I miss something?

There could also be certain assumptions in plugins that break down on Android (and AppImage/Ubuntu Touch/Debian package/Sailfish/etc.) that work on the original Kindle/Kobo/PocketBook code. Although at least on Android as long as it works it's debatable whether it's just a platform "feature" that you need to really dig around to find relevant stuff in /data/wherever.

> And... if I have defaults.persistent.lua, will I be able to make changes via the UI and have them written to defaults.persistent.lua, or will changes via the UI only be written to defaults.lua (and subject to being overwritten on OTA dev channel updates)?

That depends on what you mean by "via the UI". If you mean using the "Advanced settings" editor, then naturally it'll create a defaults.persistent.lua. If you mean using the newer built-in text editor plugin, then surely not unless you specifically tell it to (meaning you edit it and then rename it, or the other way around).

**Comment by arooni** [comment]
> > Upon further investigation the only thing that seemed like it lost track of itself was having to log into evernote again (that and the whipsersync position syncing). I didn't see an evernote config file in /settings/ ... Did I miss something?
> 
> There could also be certain assumptions in plugins that break down on Android (and AppImage/Ubuntu Touch/Debian package/Sailfish/etc.) that work on the original Kindle/Kobo/PocketBook code. Although at least on Android as long as it works it's debatable whether it's just a platform "feature" that you need to really dig around to find relevant stuff in /data/wherever.
> 
> > And... if I have defaults.persistent.lua, will I be able to make changes via the UI and have them written to defaults.persistent.lua, or will changes via the UI only be written to defaults.lua (and subject to being overwritten on OTA dev channel updates)?
> 
> That depends on what you mean by "via the UI". If you mean using the "Advanced settings" editor, then naturally it'll create a defaults.persistent.lua. If you mean using the newer built-in text editor plugin, then surely not unless you specifically tell it to (meaning you edit it and then rename it, or the other way around).

I know these questions of mine are kind of all over the place, but when I was talking about things not persisting between updates it was regarding the Kindle.  So not sure where the evernote stuff lived.  

I did create a defaults.persistent.lua via ssh.  

I guess I meant looking at the UI via setting default fonts, margins, evernote, etc...

**Comment by Frenzie** [comment]
Advanced settings is a bit hidden. It's on the file manager under tools near the end (possibly page 2).
