### ISSUE TITLE
Pocketbook OS integration

### ISSUE THREAD

**Issue by ezdiy** [koreader/koreader#6597]
Currently, pocketbook OS integration is shoddy at best, large part of it being bitrotten. This issue is to track tasks that need to be done to fix this.

- [x] **Open on power-on** book in `/mnt/ext1/system/state/current`.
- [x] **Poweroff decal** screensaver (book cover, or whatever) burned to screen right before powering off is in `/mnt/ext1/system/logo/bookcover`.
- [x] **Poweron decal** screencap koreader just before poweroff into `/mnt/ext1/system/logo/bootlogo/`
- [x] **Retain screen on de-focus**  Quite likely needed for the two above. Currently our screen blanks when OS switches focus away from us, because OS assumes we use inkview provided back-buffer.
- [x] **Switch book** - when koreader is in background, and new book opened from explorer = discover the background instance, and tell it to open the book. While this could be done through [event pipe in the past](https://github.com/koreader/koreader/pull/6559#discussion_r479684398), that one is gone for good, so we need some new way to ping the task. Just SIGUSR1 + filename in /tmp might do?
- [ ] **History** - it's possible to keep the explorer synchronized with us by telling it books we're opening via `AddLastOpen()`. Bonus: Make it stop indexing random crap.
- [x] **Exit options** - restart koreader is borked. Others like poweroff device also have OS API.
- [x] **File associations** - instead of shipping extensions.cfg, which depends on fw version, parse system extensions (or user extensions if exist), and append koreader.app to the begin/end of supported apps for each supported file.
- [x] **Wifi annoyances** The way OS handles wifi is supremely annoying, so come up with something so as to not have to babysit connect/disconnect states all the time.

ref #6321

**Comment by pazos** [comment]
another one:

- [ ] **File associations** - instead of shipping `extensions.cfg`, which depends on fw version, parse system extensions (or user extensions if exist), and append `koreader.app` to the begin/end of supported apps for each supported file.

Probably worth the time to make part of the code platform agnostic and repurpose it for other "portable" environments, like AppImage

**Comment by pazos** [comment]
> Poweroff decal screensaver burned to screen right before powering off is in /mnt/ext1/system/logo/bookcover.

I remember reading something labeled `???` in inkview documentation :smile:, good to know the file :+1: 

IIRC we need to write a png file when EVT_HIDE is received but we have some time before shutdown. Please correct me if I'm wrong :p

**Comment by ezdiy** [comment]
@pazos It's pretty messy actually, as EVT\_ does *not* ever tell us that shutdown is actually going on. I've traced the native reader and that one does indeed dump the file only during shutdown - somehow it gets the memo (same as current for the book).

As for extensions, I think just Device:associateFileExtensions({"epub", "pdf", ....}), from UIManager:init() for now, and if someone wants to do UI for that, they can. In case of PB device frontend would create new remix of extensions.cfg from that handler, other frontends doing their own thing + generic nop.

**Comment by ezdiy** [comment]
> write a png file

That's another annoying part - it's a BMP, and very specifically formatted one to boot (must be exact screen size & bpp)

**Comment by ezdiy** [comment]
Lower priority (aka wontfix unless there's a volunteer). Difficult to implementat, dubious benefit:

- [ ] **USBMS** - *hard* (due to monitor *really* wanting to kill everything). may probably require root permissions.
- [ ] **Subtasks** (aka "windows" for each open book)  - *hard*, the OS API is complex, and koreader doesn't have the notion internally

**Comment by ploum** [comment]
I see #1493 as been market as "won't fix" but could it be part of this wider issue?

**Comment by pazos** [comment]
@ploum: I labeled the old issue won't fix when I got a pocketbook to tinker with. That was before @ezdiy steped in and fixed most of PB annoyances.

Won't fix means exactly that: issue is known, nobody is going to fix it and patches welcome.

Of course @ezdiy has "superpowers" to reopen the old issue, remove the label and fix it.  If that doesn't happen then it's up to contributors to submit fixes. The same applies to all issues labeled "won't fix": https://github.com/koreader/koreader/issues?q=is%3Aissue+label%3Awontfix+is%3Aclosed

**Comment by rjd22** [comment]
@pazos can you assign this issue to me? I might finish the last few.

Most stuff should be fixed the next release like power-on and off decals and the wifi annoyances. But keeping history in sync would be a great extra feature.

**Comment by EastEriq** [comment]
I installed 2022.02, and remarked that koreader text fades off when defocusing (e.g. long-left-button press) or putting the device to sleep, as wished. I presume that switching to inkview did it, compliments. I think this can be said to have tackled task 2 and 4, at least on my device.

**Comment by rjd22** [comment]
@EastEriq yep, those 2, 3 and 4 are tackled by using inkview. Sadly I can't check them because I don't have ownership of the ticket.

**Comment by Frenzie** [comment]
@rjd22 
> Sadly I can't check them because I don't have ownership of the ticket.

You should have the relevant permissions now, including merging PRs. Please refrain from merging unless it's had a second pair of eyes or unless it's super small and obvious (example of small and obvious: https://github.com/koreader/koreader/pull/8849; example of small but not necessarily obvious: https://github.com/koreader/koreader/pull/8836).

**Comment by rjd22** [comment]
@EastEriq book tracking is not done with inkview but with a separate c library that allows you to write the page in the pocketbook library. So integrating this feature comes not for free. It will mean integrating with another library that we will need to track and hope it doesn't cause any crashes.

For this reason I decided to not integrate it because stability between all pocketbook devices is more important than tracking pages between Pocketbook and KoReader.

**Comment by EastEriq** [comment]
perfectly reasonable

**Comment by cy8aer** [comment]
I wonder what power-on decal means on pocketbooks: With the inkview path I can see a blurred text when switching to standby (like in the original reader apps). But there is no screenshot of the last page when booting up. Is there some option I need to turn on for this?

Touch Lux 3

**Comment by rjd22** [comment]
@cy8aer on my device booting up opens KoReader on the page I suspended it on. Does this work differently for you?

**Comment by cy8aer** [comment]
No, that is the same for me. But the firmware readers take a snapshot of the last page and show it when booting before the application is started so that you can read at boot time. And I thought this would be "power-on decal". It is - of course - no problem when this cannot be implemented.

**Comment by Frenzie** [comment]
On a completely different note (technically speaking) @NiLuJe @poire-z a conversation last night has convinced me that it would  be a good idea to do that for all (recent) documents. Just insta-display the last page while loading the document.

**Comment by poire-z** [comment]
I don't think it's worth the effort, and maintenance of recent/no-longer recent image cache. Also, a document that takes time opening shouldn't take much time with crengine cache...
(The good thing is we already keep displaying the previous page while re-rendering after font change :)
And I, personally as a dev, but also for users reporting issues, would rather see what's happening or not happening, that having it all masked by some full screen screenshot faking and pretending it's already all done.

**Comment by cy8aer** [comment]
As I wrote: it is no problem if it is not implemented - for me it was just a problem of understanding the term "power-on decal". 

> And I, personally as a dev, but also for users reporting issues, would rather see what's happening or not happening, that having it all masked by some full screen screenshot faking and pretending it's already all done.

Yes this sometimes confuses the user with the buildin readers. And the behaviour is crazy if you tap somewhere while booting.

**Comment by rjd22** [comment]
For the ones wondering. This is how pocketbook handles sleep right now:

https://user-images.githubusercontent.com/160743/156007609-93cdb078-3e80-4614-a085-83fa8046e75d.mp4

**Comment by Frenzie** [comment]
@poire-z 
> I don't think it's worth the effort, and maintenance of recent/no-longer recent image cache. Also, a document that takes time opening shouldn't take much time with crengine cache...

Not always true, but mostly true enough, yes. ^_^

> And I, personally as a dev, but also for users reporting issues, would rather see what's happening or not happening, that having it all masked by some full screen screenshot faking and pretending it's already all done.

The use case for quickly switching between ~3-4 documents is real enough. There's currently an acceptable but slightly annoying delay, is all. That being said, the person I was talking to was primarily familiar with Kindle being slow af. ;-)

**Comment by j4w0r** [comment]
Hi @rjd22, thanks for resolving some PB issues lately - koreader behaves stable. One last pain is using Wifi.

The Wifi annoyances are still there. This is at least the case with PB740 (Inkpad 3 - fw 6.3-6.5).
I have noticed two problems:

A) Turning off wifi in koreader does not work - in PB status bar Wifi is still on with wifi-standby mode. Moreover, after turning wifi off in koreader, returning to book, than again browsing menu/Network sometimes Wifi connection is checked, sometimes unchecked.

B) Wifi connection sometimes works, sometimes it does not - I can not find a rule.
Generally it looks like koreader thinks that wifi is on but connection is timed out. I have these issues when trying to use for example Wallabag, Wikipedia or checking for koreader updates.

Sometimes I have same behavior as in #7912 or #8871 (it looks to me as the same problem on different scenarios).
When using Wallabag I have experienced same behavior as in mentioned Issues. Also I have came accross another scenario (simmilar to #6369):
Wallabag -> Retrieve new articles -> "Do yout want to turn on Wi-Fi?" -> Wallabag "Connecting" and after a few seconds -> Wallabag "Could not login to Wallabag server"

koreader version: koreader-pocketbook-v2022.02-4-ga2b64182_2022-02-28

**Comment by ploum** [comment]
Starting with the lastest ota update (2022.02), koreader started to crash everytime the pockebook is woke up from sleep (which is when closing/opening the smart cover). PB632-V632.6x5.1383. Crash log only error is "WARN: Error when loading plugins/terminal.koplugin/main.lua".

Should I report a separate bug? (if yes, could you help me with how to provide the best relevant information/debug output about the issue?)

**Comment by Frenzie** [comment]
Is there anything you're aware of @rjd22?

@ploum Could you try the latest nightly? There are a few PB fixes like https://github.com/koreader/koreader/pull/8823 although that one doesn't sound relevant to your problem. If that doesn't help, please enable debug logging (in the file manager → tools → developer options) and post the crash.log generated that way so with any luck there's a bit more of a pointer as to where it might be going wrong.

**Comment by rjd22** [comment]
@Frenzie Nothing I am aware of. I would need to see a debug log to see what part throws an error. It might be related to the terminal issue ticket since the error happens in "plugins/terminal.koplugin/main.lua". I saw a lot of changes happended there:

https://github.com/koreader/koreader/issues/8844

@ploum does disabling the terminal plugin fix the issue for you?

**Comment by Frenzie** [comment]
@rjd22 That error just means the plugin has an error and therefore isn't loaded.

**Comment by rjd22** [comment]
@j4w0r I will be looking into the Wifi when I have some more time. Most likely I will be looking into pinging the connection with the inkview library hopefully forcing the PocketBook OS to keep the wifi active. This will cause more power draw if you forget to disable the wifi but would increase the user experience by a lot.

**Comment by ploum** [comment]
@Frenzie @rjd22 : I opened a separate issue to handle my problem to keep this issue more on topic : #8898 (hope I did well)

**Comment by NiLuJe** [comment]
I wonder if all of these aren't just duplicate of the nil task issue that's possibly exacerbated by the autosuspend plug-in?

**Comment by rjd22** [comment]
@NiLuJe most likely. When suspending the device null is written to the task meta data. So most likely the issue is fixed next release. But @ploum will need to test the nightly to confirm.

**Comment by NiLuJe** [comment]
Err, did a recent commit change anything on that front?

**Comment by ploum** [comment]
Is nightly different from OTA development channel ?  I can confirm that the bug still happen with 2022-02-16 (dev channel today). 

UPDATE : from what I saw on http://build.koreader.rocks/download/nightly/ , OTA-dev has the last nightly.

**Comment by Frenzie** [comment]
They're the same thing, yes.

**Comment by j4w0r** [comment]
@rjd22, like I said, I have these wifi issues not only when using Wallabag, but olso when using Wikipedia or koreader update.
I can test whatever scenario you can give me.
In some other wifi issue you said you have emailed pocketbook about API and NET_CONNECTED status. Maybe you could ask them about proper way of using inkview API for: turning wifi on/off, standby/wake, connecting/disconnecting etc so we can minimize trial and error :).

**Comment by rjd22** [comment]
@j4w0r sadly using inkview for wifi might not be possible. If I remember correctly some older pocketbook devices we still support don't have all API methods included causing them to break when using the inkview API for wifi connection.

I will be looking into it if I can improve things.

**Comment by j4w0r** [comment]
@rjd22, if we face such problems handling wifi across different pocketbook devices (you mentioned that older devices do not have all API methods) maybe koreader could support more than one (legacy) way of handling wifi and add another implementation for newer devices? Instead of tweaking/hacking this legacy way to fit all devices.

**Comment by NiLuJe** [comment]
You're still left with a massive maintenance chore of knowing which device supports what, which is a bit of a nightmare already, given the vast number of PB devices and their history ;).

**Comment by TiberiusRegenschein** [comment]
Happy to help with testing. I have a PB623 with a 4.4 firmware and a PB741 with 6.5 firmware spanning a time from 2021 - 2022. koreader is working very well on both and the hope is that devices in between are hopefully not using so many specific features of the firmware that a solution working for both devices may also work on the devices in between

**Comment by peterrus** [comment]
FYI just tested latest nightly on a Pocketbook Touch HD3 (https://build.koreader.rocks/download/nightly/v2022.03.1-41-gf37699a1_2022-04-24/) and the wifi issue still persists, in case there were any doubts about that. Toggling wifi through the native menu's (Task manager/Pocketbook settings) seems to be a reliable way to get the network connection working again for a while.

**Comment by rjd22** [comment]
@NiLuJe @Frenzie I'm working on trying to keep the wifi active. I'm kind of facing the problem that I need to call a ping method every 30 seconds or so to avoid pocketbook from closing the connection. I was experimenting with doing so but I noticed that if I try to do this in a `while true do` loop I seem to be locking the main thread there. Is there a way in the koreader lua to call a method without locking the main thread?

This was the code I was using:

```lua
function PocketBook:initNetworkManager(NetworkMgr)
    -- Snip: more stuff normally here

    function NetworkMgr:isWifiOn()
        return band(inkview.QueryNetwork(), C.NET_CONNECTED) ~= 0
    end


    logger.info('start keep alive')
    logger.info(tonumber(os.clock() + 30))
    logger.info(os.clock())

    local waitWifiPoll = 0;

    while true do
        if os.clock() > waitWifiPoll then
            logger.info('ping wifi keep alive')
            logger.info(os.clock())
            logger.info(waitWifiPoll)

            if NetworkMgr:isWifiOn() then
                inkview.NetMgrPing();
            end

            waitWifiPoll = tonumber(os.clock() + 30)
            logger.info(waitWifiPoll)
        end
    end
end
```

**Comment by Frenzie** [comment]
Generally we use http://koreader.rocks/doc/modules/ui.uimanager.html#UIManager:scheduleIn

**Comment by rjd22** [comment]
@Frenzie thank you! I adapted the code to make use of scheduleIn. Hopefully we can finally get rid of the biggest PocketBook annoyance:

https://github.com/koreader/koreader/pull/9208

**Comment by rjd22** [comment]
Closing this one. Most wifi annoyances should be gone now with wifi keep alive also integrated. Book history seems not to be working as expected and there are no other api's available so that won't be fixed.

**Comment by peterrus** [comment]
@rjd22 Great stuff (: Wifi is definitely more usable now and while I did have some quirks one time it seems to be stable generally! I can imagine the keepalive ping draining the battery a little bit but in practice it might not pose any problems.

Regardless: Thanks, my Pocketbook is perfect now!

**Comment by dziurka** [comment]
@rjd22 I tested koreader on my PocketBook Touch Lux 4 for a few days and I see that WiFi problem still persists 😕

Any action which requires a WiFi connection is useless because "wifi turn on alert" appears. Even when I turned on WiFi through this pop-up, nothing happens afterwards.

**Comment by von-nihil** [comment]
I'm experiencing the same problem as @dziurka . I'm using an InkPad 3 with the latest version of KOReader (2022-11).

When I try to perform any action the requires Wifi, it simply cannot get a connection (e.g. for downloading dictionaries, Wikipedia etc). As a workaround, opening the PB built in web browser in the background allows KOReader to acquire/maintain a connection and perform the desired actions.

From digging around, it looks like this was fixed a while ago and so my experience is a regression. Could this be anything to do with the new PocketBook firmware released over the summer of 2022?

**Comment by EastEriq** [comment]
With regards to the last task which is to date unchecked, History: recently [this](https://github.com/koreader/koreader/assets/16066531/751c5359-fe5d-40f5-993b-67728b633187) came up in the pocketbook mobiread forum, pointing to [this script on github](https://github.com/jjrrw174/PocketBook-Sync-KoReader-progress-with-PB-Library), which might be a start.

**Comment by sdasda7777** [comment]
@ezdiy Hi, I'm sorry to bother you, but could you please clarify how this feature is supposed to work? Could you link related PRs or something? I came up with nothing when searching either the manual or the repo.

>  [x] Open on power-on book in `/mnt/ext1/system/state/current`.

**Comment by liskin** [comment]
> @ezdiy Hi, I'm sorry to bother you, but could you please clarify how this feature is supposed to work? Could you link related PRs or something? I came up with nothing when searching either the manual or the repo.
> 
> > [x] Open on power-on book in `/mnt/ext1/system/state/current`.

If you associate some file extensions to KOReader, this _just works_. To do so, open top menu, then ⚙ → Device → Associate file extensions, and tick at least epub, epub3, pdf, and any other formats that you use. Then it should just work—PocketBook opens the last book on start, KOReader tells it which one, and if the format is associated to be opened in KOReader, everything fits together. :-)

**Comment by sdasda7777** [comment]
It does work! That's awesome, thanks!

**Comment by liskin** [comment]
> With regards to the last task which is to date unchecked, History: recently [this](https://www.mobileread.com/forums/showthread.php?t=354026) came up in the pocketbook mobiread forum, pointing to [this script on github](https://github.com/jjrrw174/PocketBook-Sync-KoReader-progress-with-PB-Library), which might be a start.

There's a (somewhat) maintained koreader plugin that probably evolved from that at https://github.com/ckilb/pocketbooksync.koplugin
I've been using it for a couple months, and been contributing fixes and PR reviews as well. Perhaps it's mature enough to be included in KOReader itself, and we can tick the "History" box at last? :-)

**Comment by sdasda7777** [comment]
> It does work! That's awesome, thanks!

If I may have one more question, should the cover image when the reader is turned off be working as well? For me it doesn't currently seem to work, it shows a cover of a book that read few months ago (it could be the last book opened in the system reader app, but I'm not completely sure).

**Comment by liskin** [comment]
> If I may have one more question, should the cover image when the reader is turned off be working as well? For me it doesn't currently seem to work, it shows a cover of a book that read few months ago (it could be the last book opened in the system reader app, but I'm not completely sure).

I think that needs to be manually enabled as well: ⚙ → Screen -> Cover image and enable Save cover image. Might need to set the path to default as well, possibly (been quite a while since I did that on my device).

**Comment by sdasda7777** [comment]
Thanks! It didn't work for me initially, but I followed the steps on [the plugin page](https://github-wiki-see.page/m/koreader/koreader/wiki/Coverimage), and now it seems to work perfectly! It seems that you have to set the Pocketbook to display `Random` image, and also possibly set KOreader to save as grayscale BMP in the `Size, background and format` submenu. Again, thank you so much!
