### ISSUE TITLE
Translation languages fixed per book

### ISSUE THREAD

**Issue by davidvelosa** [koreader/koreader#8063]
First and foremost, Thanks for everything Koreader Team 👍 👍 👍  you have managed to make Koreader my main reading app for months now!! Now to the point...

**Does your feature request involve difficulty completing a task? Please describe.**
As a multiple language book reader I find myself too often going to the translation settings (menu and two sub-menus), to change the language to translate from (say German - Spanish -> French - Spanish -> Italian - Spanish), since it´s a global setting instead of a "per book" setting. 
The auto-detect language option most of the times, specially with single words or borrowed words, proof not to be trustworthy. Particularly because google fetches the word from all the available languages on their database, and this makes it very inaccurate. So I don't find it a reliable solution, or even usable in my case.

**Describe the solution you'd like**
I think there can be a couple of simple solutions. The most functional and doable:
1. Fix the translation settings to each book. So they can be saved like any other personalized settings. Let's say a checkbox in the translation menu, to remember or save the translation settings of this given book. 
OR, simply make the setting automatic for all books, so you only need to change it once, after opening the book for the first time. (even maybe auto-detect the book language? and make it the starting 'Translate From' setting)

An add-on, to make everything simpler on the translation settings in the long run:
2. Add the option to hide / show languages on the Language list (translate from:, translate to:), to make them easier to find. Like the one found on Plugin Management

**Describe alternatives you've considered**
Not at all necessary but would be nice:
3. Add drop down menus to select languages (from/ to) in the translation box / dialog, better if limiting the languages and chosen by the user. This would make everything easier usability-wise, but probably not the easiest one to execute.

Thanks for any help or possible solutions :)

**Comment by poire-z** [comment]
> The auto-detect language option most of the times, specially with single words or borrowed words, proof not to be trustworthy.

Just curious, can you give us real examples ?

Drop down menus in the translation result window is hard work, and would add noise for 99% of use cases where the auto-detect is just fine.
Per-book settings vs global is always a bit painful to implement - and so is having it clear in the menu which is the document specific one vs the global one for next documents...

The simplest I could come up with that did not require much work is to have an option (also global) to use the book's medatata language tag as the source language. It's present in most EPUBs, but usually not in PDFs. There's currently no way to set a lang tag to a book without one in its metadata.
We then could get the following, with a bit of dynamic (not super obvious, but that's the best I could come up with) for the enable/check state of the 3 settings - the first document is a book with lang=fr, the 2nd document is one without any lang=:

<kbd>![translator1](https://user-images.githubusercontent.com/24273478/129556895-0734927d-0847-4279-9ae7-f98c1280fde4.gif)</kbd>

Would that be helpful enough ?  
The auto-detect is just fine when you read in your native language and have text fragments in foreign languages here and there in the book.
That new option could then be useful if the book main language is not your native ones and you want to be really sure of not bad-detection - but then you're alone with foreign language text fragments. Not sure it's that preferable.

**Comment by davidvelosa** [comment]
> Just curious, can you give us real examples ?

Sure I can! I will leave the examples at the end :)

> Drop down menus in the translation result window is hard work, and would add noise for 99% of use cases where the auto-detect is just fine.

I can imagine is not easy to do. Now that you mention it just came to my mind a button like the one found on Wikipedia where you can switch between languages (FR>EN). but in the Translate case, instead of languages, change between (Auto-Detect > Translate From > Book Language > Auto-Detect), to have it more accessible. BUT definitely not at all necessary taking in account your current solution.

> The simplest I could come up with that did not require much work is to have an option (also global) to use the book's medatata language tag as the source language. It's present in most EPUBs, but usually not in PDFs. There's currently no way to set a lang tag to a book without one in its metadata.

Personally I don't read literature on PDFs (though it might be the case for some people), however there's the Calibre conversion option or the edit metadata in these case scenarios. Maybe do a disclaimer of this exception with PDFs?

> That new option could then be useful if the book main language is not your native ones and you want to be really sure of not bad-detection - but then you're alone with foreign language text fragments. Not sure it's that preferable.

In my particular case, it is. It would work like a charm for me. And I will be very glad if it gets implemented! 😄😄👍 
Most foreign language words (names, places, concepts) can go through Wikipedia and get an acceptable result, in case is needed.

**NOW THE EXAMPLES...**
Sadly, this time I didn't happen to find any Swahili word in a French classic :P but I hope they are enough to make you an idea, and make my point as well.

Thanks for reading and all of your help! 

**EXAMPLE NO. 1:** 
Italian book, I translate 'Foro'
Auto-detects: Spanish. 
'foro' in Spanish: let's say is like Forum in English.
'foro' in italian: Hole. 
These words are called false friends (they have the same writing, or alike, but different meaning), they exist in most common languages, and hard to auto-detect.

<img src='https://user-images.githubusercontent.com/78831040/129598958-54490216-ae80-4698-9aff-de6ac9432788.png' width="350px">
<img src='https://user-images.githubusercontent.com/78831040/129589811-8fbee2d3-1706-4e04-be17-d9baa70974a5.png' width="350px">
<img src='https://user-images.githubusercontent.com/78831040/129589844-77e0f063-a06a-43f6-b621-64e614cc1aa8.png' width="350px">

**EXAMPLE NO.2:**
French book, I translate 'midi'
Auto-detects: English
'Midi' in English: dress / musical standard
'Midi' in French: midday / noon

<img src='https://user-images.githubusercontent.com/78831040/129591252-7d12a8f4-e906-4f58-966e-f69040c4145e.png' width="350px">
<img src='https://user-images.githubusercontent.com/78831040/129591952-3dbc2a02-e214-4b8c-bbd5-acaa57f47b15.png' width="350px">
<img src='https://user-images.githubusercontent.com/78831040/129592057-ff9a1278-dd1d-4590-a913-c650fbc9f385.png' width="350px">


**EXAMPLE NO.3:**
French book, I translate 'main'
Auto-detects: English
'main' in English: most important / principal / chief
'main' in French: hand

<img src='https://user-images.githubusercontent.com/78831040/129592454-95b7f4d6-7427-4138-b794-e4f9cd1e0a13.png' width="350px">
<img src='https://user-images.githubusercontent.com/78831040/129592568-8f943dd4-1ce5-4ef2-a58c-9b94dd94c0b7.png' width="350px">
<img src='https://user-images.githubusercontent.com/78831040/129592627-b47e5375-2a26-46ad-839b-f74f4e3c8aaf.png' width="350px">


**EXAMPLE NO.4:**
Japanese book, I translate '某街道'
Auto-detects: Chinese
'某街道' in Chinese: a street
'某街道' in Japanese: a certain highway
Let's say this last one is not too far, but will make the context very different.

<img src='https://user-images.githubusercontent.com/78831040/129593496-f1be8ed1-64d2-4f87-86eb-a094624fa9e7.png' width="350px">
<img src='https://user-images.githubusercontent.com/78831040/129593578-0df3776e-46ee-4079-982e-716f21b26fc6.png' width="350px">
<img src='https://user-images.githubusercontent.com/78831040/129593651-e6359a71-144c-4b6a-b7c0-245a0f4ff867.png' width="350px">

**Comment by poire-z** [comment]
> In my particular case, it is. It would work like a charm for me. And I will be very glad if it gets implemented! 

Good. You can test how this works and give some feedback by replacing your koreader/frontend/ui/translator.lua and koreaer/frontend/apps/reader/modules/readertypography.lua with these ones (remove the .txt extension, needed for github to accept this file upload):
[translator.lua.txt](https://github.com/koreader/koreader/files/6994339/translator.lua.txt)
[readertypography.lua.txt](https://github.com/koreader/koreader/files/6994344/readertypography.lua.txt)

Thank you for the examples. I see you do single words translation so to get definitions - and misdetections is easier with single words.
But if you would select the sentence or a part of it, it would probably work as it would have more context for the detection - and you'll probably find the most correct definition in the translated phrase - instead of having to real all the possible definitions and find out the one that apply to the context.
Would you still prefer single word translations ?

Btw, what's your font on these screenshots ? Somehow, it looks a bit like what I usually see in screenshots of Kobo's Nickel app - I rarely see KOReader screenshots looking that similar.

I see you can read japanese with ruby :) - how our ruby support #6305 works for you ? We didn't get much feedback, and I'm curious.

**Comment by davidvelosa** [comment]
> You can test how this works and give some feedback

Thank you once again! I just replaced them and so far so good 👍👍

> Would you still prefer single word translations ?

Good question. In fact it depends on the context.
To tell you the truth I use both, and depending on the situation. Mostly, I translate complete phrases because one word only can be misleading. But there are phrases that even completely translated don't make sense on the context, just because Google decides to translate a word with one meaning only instead of putting the other possible options. You only get one unique translation in phrases. So when this happens you have to look for the single word instead, just to make a sense out of the phrase and arrive to your own conclusion. Also Google lacks a lot on idiomatic expressions, and will just make literal translations in most of the cases, but this varies from language to language. Anyways, some times I understand everything and I'm just missing one word, so no need to take the whole phrase, but with auto-detect, it becomes hit and miss. The other reason is when I translate something, I make a note as well including the meaning of the word, so For me it doesn't makes sense to highlight a whole phrase to cancel everything and just highlight what I need in order to make the note, just because the translator uses other languages on single words. After a while it becomes tiring. 
The bottom line is that Google does the trick, but man can't trust 100% on it 

A quick example:
'Faire la grasse matinée'
Literal translation (usually google's): to do a fat morning.
Figurative translation: to stay in bed until late in the morning. (which ironically appears in the French - Spanish translation but not on the French - English)

In these cases I use Reverso Context since takes all of these things in account. 

> Btw, what's your font on these screenshots ? Somehow, it looks a bit like what I usually see in screenshots of Kobo's Nickel app - I rarely see KOReader screenshots looking that similar.

You have good eye. The font is called Georgia, and yes, it's included in Kobo's Nickel app. This is the one I found easier and nicer to read in the long run :) Serif type fonts help you read a little faster and are more comfortable to your eye for long reads. A graphic designer's word ;)

> I see you can read japanese with ruby :) - how our ruby support #6305 works for you ? We didn't get much feedback, and I'm curious.

Well, it works :D

Only two things to point out if you ask me would be: 
1. Font for the ruby characters, would be nice to have the option to use a different one from the font on the current file, specially one that can be more readable (ex. in my screenshot, a sans serif for the furigana /ruby only), doesn't matter if it's a global setting only.
2. The spacing between the characters and the furigana / ruby was a little funky in the past, if it can be customizable in some way that would be nice (probably it's already been solved, but it's been a while since I don't play with the japanese books)

...And vertical reading right to left, but that's a whole different beast and thread I suppose 👹👹👹

Thanks for the support @poire-z you are the man! 
__________________________

PD:

I just reminded two other issues that I had and forgot to point them previously, just leaving them here FYI maybe you were not aware:

1. Trying to connect a Kobo Libra to a Cellular Hotspot network (Iphone 7) for Wifi was impossible
2. I'm finding the high memory usage issue on the 130 - 160 mark, when I'm heavy highlighting stuff and translating, it just crashes and all the highlights get lost, which doesn't make sense. Ironically started after having solved #7627 (or maybe I was not heavy highlighting in that point). I solved it with the high memory usage alert and restarting on the 135 mark

**Comment by poire-z** [comment]
Thanks for testing. I'll push these changes later then.
Will need some small `help_text=` on Auto detect and From book language to give some hint about when to use each of them.

About ruby:
- for the font, we follow the publisher styling - or use only your main selected fonts (and the fallback fonts) - we don't know what other font could be good for what text we may find in ruby. So we can't do much generically.
- for the spacing, I had some hard time finding values that looked ok - but I didn't really know what look to expect.

Anyway, _you_ can customize this to your liking with a user style tweak.
We have in our epub.css:
```css
/* Ruby support */
ruby {
    /* These will have no effect when ruby is reset to display: inline */
    text-align: center;
    text-indent: 0;
}
rb, rubyBox[T=rb] {
    line-height: 1;
}
rt, rubyBox[T=rt] {
    line-height: 1.2;
    font-size: 50%;
    font-variant-east-asian: ruby;
    -cr-hint: text-selection-skip;
}
```
So, you could make a style tweak with:
```css
rt, rubyBox[T=rt] {
    font-family: "My nice Japanese Sans";
    line-height: 1.4; /* whatever works for you */
}
```
and apply that tweak whenever you need it.

> ...And vertical reading right to left, but that's a whole different beast and thread I suppose

There is already one thread (and not much hope): https://github.com/koreader/koreader/issues/4353#issuecomment-452452412

**Comment by davidvelosa** [comment]
> Will need some small `help_text=` on Auto detect and From book language to give some hint about when to use each of them.

Quick idea:

Auto-detect: 
- Best suited for foreign phrases or texts on books in your native language.

Translate from:
- User defined source language (global)

From book language: 
- For books in your non-native language, where consistent translation is needed and foreign words are exceptional on the text.
- For books in your native language, to define unknown words.
!the file needs to have 'lang=' defined in meta for language detection (present in most .EPUBs)!


> Anyway, you can customize this to your liking with a user style tweak.

Thanks for the info! Have been playing with it a little bit, so you can make yourself an idea of what I meant.
It might not seem too different, but in long reads is much less intrusive and standardized as an initial setup. Maybe you guys can consider it in the future to make it a great starting point on files :)

NO TWEAKING (on the left), TWEAKING (on the right)

<p float="left">
  <img src="https://user-images.githubusercontent.com/78831040/129772907-7b910691-f24c-4da2-a3e6-00c0e52d8d9e.png" width="45%" />
  <img src="https://user-images.githubusercontent.com/78831040/129773678-cd6c592c-203d-410e-b8d7-4dac4f4a29f0.png" width="45%" /> 
</p>

The settings were:

```css
rt, rubyBox[T=rt] {
    font-family: "Noto Sans JP";
    line-height: 1.6;
    text-size: 35%; /* 40% is good as well */
    font-weight: 400 /* 500 is good as well, but it might start to intrude in my opinion */
}
```

**Comment by poire-z** [comment]
Thank you, I added your suggestions to #8094. A bit rewritten because (I think) we mostly have all of our help_text as normal sentences (and not just declaration/definitions like your suggestions).

Please re-read them (@Frenzie @NiLuJe too), I'm so unsure with stuff like "on text", "with text", "in the text" :) with English - and suggests rewording there.

**Comment by poire-z** [comment]
> Maybe you guys can consider it in the future to make it a great starting point on files :)
```css
rt, rubyBox[T=rt] {
    font-family: "Noto Sans JP";
    line-height: 1.6;
    text-size: 35%; /* 40% is better */
    font-weight: 400 /* 500 is good as well, but it might start to intrude in my opinion */
}
```

We do ship Noto Sans CJK, so we could force the use of this specific font with ruby:
- it will be used instead of the specific installed and selected JP/CJK font the user has selected (as the main font, or the first fallback font) - but I'm not sure it's good we force impose this.
- but it would be used also with latin/western text that would use RUBY for some specific effect - so instead of the main font
For this reason, this (and/or part of the ones below) could be added as shipped style tweaks (we have room in `Style tweaks > Text > Hyphenation, ligatures, ruby`)

`font-weight: 400`  is the default weight. What's the reason for adding it ? So that ruby on bold base text is not itself bold ? If that's a publisher rule (I haven't checked how browsers do), this may be added to epub.css - or declined as a style tweak.

About `line-height: 1.6; text-size: 35%; `, I dunno if this specific setting work with your main font vs. Noto Sans ruby, to adjust for the possible differences in internal font line-heights/size - or if it would work as well with both base and ruby font being the same (both Noto Sans, or both your main font).
If it work fine in all cases, this can be added to epub.css - or declined as a style tweak.

**Comment by davidvelosa** [comment]
> Thank you, I added your suggestions to #8094. 

Fine for me 👍

> For this reason, this (and/or part of the ones below) could be added as shipped style tweaks (we have room in Style tweaks > Text > Hyphenation, ligatures, ruby)

I don't know the implications, but in the Page menu, where Font is found it could become `Fonts > 1. Font 2. Ruby Font`.
Otherwise it could be included right where you say `Style tweaks > Text > Hyphenation, ligatures, ruby` > Ruby font, to give the option be the same font as the main one or use a different one 

 > font-weight: 400 is the default weight. What's the reason for adding it ?

Just for reference, Regular size. 👍  If it's lighter (but can be, read the size explanation) risks of getting lost. If it's heavier, risks of starting to fight with the main text for attention

> About line-height: 1.6; text-size: 35%; , I dunno if this specific setting work with your main font vs. Noto Sans ruby, to adjust for the possible differences in internal font line-heights/size - or if it would work as well with both base and ruby font being the same (both Noto Sans, or both your main font).

Noto Sans CJK and Noto Sans JP are very much alike (possibly the same, just different foundry), I just used the JP version because I didn't realized that CJK had Japanese characters. So then I tested the CJK and looks the same to me at ruby size. 

That said, about the line height:
It is to give enough upper space to the main characters, because it would start look too piled up, specially if the default line height (between main line and main line) is too reduced (about 80 or less). And since this works on relative sizes the less line height space, the more the ruby characters and main characters will start to overlap. Line heights are weird, so probably is good to treat ruby and main line height individually

I did some quick tests, will leave them below.  You want the ruby characters to be just above, but not too up so they end up right between lines (the problem I addressed you when you asked me at the beginning, and another reason why using a general line height for all probably wouldn't be good)


WITH CURRENT RUBY LINE HEIGHT (Main Line Spacing 80, 90)

<p float="left">
  <img src="https://user-images.githubusercontent.com/78831040/129804407-f91e110f-ca99-4506-a206-2439c9b13ee4.png" width="45%" />
  <img src="https://user-images.githubusercontent.com/78831040/129804412-b5be4a1f-354d-4050-b670-02760e53740e.png" width="45%" /> 
</p>

WITH RUBY 1.6 LINE HEIGHT, 40% SIZE (Main Line Spacing 80, 90 and 100 respectively):
<p float="left">
  <img src="https://user-images.githubusercontent.com/78831040/129804402-bd5e6524-3b38-46f5-8ccb-fa0fdb120dba.png" width="32%" />
  <img src="https://user-images.githubusercontent.com/78831040/129804404-af2a247b-2420-42ce-ba9d-db1a59eb229b.png" width="32%" /> 
 <img src="https://user-images.githubusercontent.com/78831040/129804405-c2cb1e6d-dada-401a-b1a3-398d181cb444.png" width="32%" /> 
</p>


About the size: 
Specially in the Sans fonts, they can be smaller without losing legibility (with Serif fonts this can change from font to font). In real world they don't need and they aren't big, in the example below from a manga (about 15cm tall) the 'ruby' text is 1mm height. And in the page from my Kobo Libra font size 26 and ruby size 40% the ruby real world size is 1.5 mm. This is applicable to e-ink screens, in other types of screen the type pixel density can affect, but seeing Asian characters in a low density screen often requires bigger text sizes 🤷‍♂️, so this would be proportional.

<img src="https://user-images.githubusercontent.com/78831040/129804233-ca09f967-1089-4202-89e9-aa680f8e8d0e.png" width="600px" />

**Comment by poire-z** [comment]
> I don't know the implications, but in the Page menu, where Font is found it could become Fonts > 1. Font 2. Ruby Font.

The implications are huge ! and the ruby readers so little to have another option most people won't understand - so let's forget it.

> Noto Sans CJK and Noto Sans JP are very much alike (possibly the same, just different foundry), I just used the JP version because I didn't realized that CJK had Japanese characters. So then I tested the CJK and looks the same to me at ruby size. (the tests I made are with CJK)

Yes, they are the same, same foundry, same glyphs - CH-Simplified/CH-Traditional/JP/KO glyphs are all there and picked up from the lang= tag (or lang set via Typography) we give to the font when asking for a glyph. The various JP or CH instances just set a different default lang= for when the software is not giving any lang hint.

About line heights, it's been a while since I tried to have it right.
See #6223 for the kind of issues I had to fight. Haven't re-read it, but I think one important target was that if there's a line that has no ruby (which I don't see in your samples above), we should try to keep the same visual line height, so we don't get uneven line-heights. But opening my ruby test files, I see we get uneven line heights... so I guess gave up on that :) or just tried to have these not extra different - also check for that with your tuning.

**Comment by davidvelosa** [comment]
> The implications are huge ! and the ruby readers so little to have another option most people won't understand - so let's forget it.

Yeah, I could imagine. Maybe leave it in style tweaks > ruby in the future.

> About line heights, it's been a while since I tried to have it right.

I think you did a great job, line heights look fine to me! 

Sorry for the squares, they are just an approximate but same height. I'm using my tuning down below but line height works the same with the stock settings.

<p float="left">
  <img src="https://user-images.githubusercontent.com/78831040/129819180-774a2600-2788-458d-8bc2-03e184a9641c.png" width="45%" />
  <img src="https://user-images.githubusercontent.com/78831040/129819181-befc6f8e-f6f3-47b3-a053-b14582dc968b.png" width="45%" /> 
<img src="https://user-images.githubusercontent.com/78831040/129819182-a63fca15-5f6a-4997-a5b3-a7426112a40f.png" width="45%" /> 
</p>

Thanks for your help on my issue once again! Really appreciated 🙌

**Comment by poire-z** [comment]
Looks fine : what's your line spacing % on these screenshots ?

Sharing my test file, with various ruby construcs (nested, ruby up and below text, non-CJK ruby...): [test-ruby2.html.txt](https://github.com/koreader/koreader/files/7005031/test-ruby2.html.txt)
Check how your tuning works with all of these (all of these may not all work with current tuning, no need to have them work, you just need to be sure your tuning doesn't make too many of them look worse :)

Once you're satisfied with your tuning, tell me again what you came up with (hard to follow the discussion above when I don't read ruby :) and if you think it can go into epub.css - and/or if there's still some suggestive feeling that may not appeal to all, what can be the default and if/what variations can be made into style tweaks.

Note that we can't style much: publishers may/should already style ruby enough so it looks good (at minima, they should increase the paragraph line height). If they don't, we can't do much by default or we risk to mess with normal text. The user can still help correcting it easily with our Line Spacing setting - or less easily by making style tweaks.

**Comment by poire-z** [comment]
> font-weight: 400 is the default weight. What's the reason for adding it ? So that ruby on bold base text is not itself bold ? If that's a publisher rule (I haven't checked how browsers do)

Did: Firefox and Edge do bold the ruby as much as the base:
![image](https://user-images.githubusercontent.com/24273478/129855575-1c0eee26-869b-4b9b-8b05-28beed3efab5.png)

**Comment by davidvelosa** [comment]
> Looks fine : what's your line spacing % on these screenshots ?

Line Spacing from Koreader is 100 (don't know the equivalence on css, 100%?), but I was using on `rt, rubyBox[T=rt] {line-height:1.6}`, more on that at the end

> Check how your tuning works with all of these 

**Short answer:** you need minimum a `body {line-height:2}` or the equivalent in Computer / Koreader to make your file work.

**Longer answer:** And this has kind of a logic reason,

-If ruby `<rt>` adds a 0.5 box height to your text body, you will need at least `line-heght:1.5`
-If you add a `double <rt>` or `<rt> and <rtc>`, your text body will need `line-height:2` to be able to show everything
-if you add `double <rt> and double <rtc>`, the logic should continue, `line-height:2.5` and so on...

So if your height line is not high enough to carry everything, it will just open up. But maybe this you knew already. 
What is not so evident is that layout design guidelines change with Asiatic languages. If with latin characters the optimal line spacing is around 1.15-1.20x of your text size; from what I read in some blogs today, the recommended line spacing with on Asian texts is 10-15% more (1.3-1.45x), even saw a good 1.5-2x. And this last one makes more sense for me.

Some samples... (after doing the samples I just realized that latin characters do something to the line, but in 200 is almost imperceptible)

<p float="left">
  <img src="https://user-images.githubusercontent.com/78831040/130001953-2d7f65c9-def1-4394-a15f-7efa9f28846b.png" width="45%" />
</p>
<p float="left">
  <img src="https://user-images.githubusercontent.com/78831040/130002045-ed7f9cc5-4242-4ecd-941e-1a4e59836834.png" width="45%" />
  <img src="https://user-images.githubusercontent.com/78831040/130002051-3a268ce7-ec01-4be3-9506-5ae2b1ddbc4c.png" width="45%" /> 
</p>
<p float="left">
  <img src="https://user-images.githubusercontent.com/78831040/130002193-5414ec09-011d-4cd6-9c73-f9b1ec446288.png" width="45%" />
  <img src="https://user-images.githubusercontent.com/78831040/130002190-fbc3ec91-9728-42d9-ad46-a4f3d01fbe6c.png" width="45%" /> 
</p>

**Now to the real world :) :** 
- `Single <rt>` or `nonexistent <rt>` lines are more common in asian language books, based in my short experience. Japanese adult books normally use it to give a pronunciation hint on rare kanjis. On the other hand, `<rt>`'s are all over teenager Japanese books.  
- Double `<rt>,<rtc>` are not so common and probably will be used in particular intentional cases. So if I was the editor / designer probably I would be aware and consider a 2x line height if `double <rt>` exist all over my book. But if that only happens once or twice in the whole file, probably I won't give a S because I'm not going to print it, lol ;)
I think 1.5 would be the the standard in Asia, and might be the minimum as well.

Can you detect ruby tags on a file, like you did to solve my problem? 
Ideas for possible solutions on uneven line heights:
When `<rt>` is present, set a minimum line-height: 1.5  / Line spacing setting: 135-150 minimum (or put at least a warning)
When `<rt>, <rtc>` are present, set a minimum line-height:  2 / Line spacing setting: 180-200 minimum (or put at least a warning)
This is to avoid uneven lines. It can be acceptable with lesser values (`<rt>` 120/ `<rt><rtc>` 160, with some uneven lines), but I think that depends on the final user to take it or leave it.

**Styling**
I checked your file both on the  computer and Koreader. With the Inline CSS it was behaving differently on the computer, so I moved to Koreader, where I saw the irregular lines you told me about, but you have an answer already on that.

- First and foremost I decided to drop the line-height to 1 on `rt, rubyBox[T=rt]` since it bases on the main text height-line and makes it inconsistent when you change Line Spacing Settings. 

- Here is my "global" solution:
 
```css

/*custom book style ruby.css*/

/* I'm aware this varies from file to file */
body {line-height: 1.5} /* Or 2, like discussed above eg. your sample file. */

/* These next two to create a nice and consistent space between main text and ruby */

rt {padding-bottom:2%}
rtc {padding-top:2%} /* rtc didn't work yet, but is it that important? :P */

rt, rubyBox[T=rt]{
     font-family; “Noto Sans CJK SC”; /* There could be another one without this to keep the original font */
     font-size: 40%;
     font-weight: 400;
     line-height:1;
}
```

> Note that we can't style much: publishers may/should already style ruby enough so it looks good (at minima, they should increase the paragraph line height). If they don't, we can't do much by default or we risk to mess with normal text.

From what I've seen, they don't on ruby. But I might be wrong on this one. 

>Did: Firefox and Edge do bold the ruby as much as the base:

Yeah, I kind of suspected that, now you see why `font-weight:400;` can be a good idea

**Comment by poire-z** [comment]
> Line Spacing from Koreader is 100 (don't know the equivalence on css, 100%?), 

Our "Line Spacing" config happens after: it justs scale all CSS line-height by this %. Browsers don't have that.
By default, CSS must be [line-height: normal](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height) and for us, it'is `line-height: 1` = we use the font natural line-height as set by the designer: we don't add any blank above or below the glyphs.
Our users can then use Line Spacing to tweak that.

> From what I've seen, they don't on ruby. But I might be wrong on this one.

Well, they should. Not styling rb and rt, but they should set larger line-height on the paragraphs that contains some ruby.

I'm still unsure what you're focusing on:
**A.** our epub.css, our default user agent stylesheet, where we have these ruby hacks to handle it via inline-tables (and we can tweak our hacks to make the behave as well as possible)
**B.** some proposed style tweak(s) to allow the user to get (at his own risks, overriding publisher's choices) better looking results - with possible side effects on other non-ruby text.

With A, we must behave as the CSS specs say and as most browsers do : we can't take any liberty in styling, we should be as bland as possible, so publisher's styles apply on that.
With B, there, we can tweak things to look better in the absence of publisher's style.

> Is it possible for you to detect ruby tags on a file, like you did to solve my problem?

I did what ? :)
But hardly possible - at least, I can't think on any obvious way to do that (or that would not add kludge different that the kind of stuff we already have, that we'd not want to have triggered on the 99% books that don't have any ruby).
I was going to say we must behave as browsers which don't detect this and do nothing, ie Firefox:
![image](https://user-images.githubusercontent.com/24273478/130022286-3fd1e04c-c24c-4f5c-b1de-6d824eaa66d6.png)
But it seems Edge does something !:
![image](https://user-images.githubusercontent.com/24273478/130022480-826124ed-baf4-4b99-b243-695f30afde73.png)
but it messes with the hello and blahblah - so I'm not going to trust it :)
Anyway, it feels that per CSS specs, we should not do anything special (the presence of ruby should not escalate back to arbitrary changing the line-height of the paragraph that contains it): the Firefox rendering is the right one.

> Yeah, I kind of suspected that, now you see why font-weight:400; can be a good idea

It's not a good idea :) If the text is font-weight: 200 to make it lighter, we don't want rt bolder than their base :)
But we set `font-variant-east-asian: ruby;`, which should pick different glyphs from the font if it provides some (and I think Noto Sans CJK does provide them, there are thinner and less "serif", or am I dreaming it? :)

For our A case (epub.css), I think we can't do much more than playing with both rb and rt line-height and the rt font-size. Anything else is too dedicated styling - but that may come into B.

> I decided to drop the line-height to 1 

For A, your allowed tweaks would come down to:
```diff
 rb, rubyBox[T=rb] {
     line-height: 1;
 }
 rt, rubyBox[T=rt] {
-    line-height: 1.2;
-    font-size: 50%;
+    line-height: 1;
+    font-size: 40%;
     font-variant-east-asian: ruby;
     -cr-hint: text-selection-skip;
 }
```
Which would before/after:
![image](https://user-images.githubusercontent.com/24273478/130024800-ab4dd595-267d-4690-b151-57e4b51c7c92.png) Before
![image](https://user-images.githubusercontent.com/24273478/130024852-01cad401-3fc5-4495-bad7-2f4cf8a5421b.png) After

"After" feels a bit smaller and hard to read - but what do I know :) So, if you think that's best, it could go in A. Also please check with other CJK fonts it's as fine.
But if it's too personal, it all can go in B.

(Didn't add `rt {padding-bottom:2%}`, feels wrong for RT below the text :)haven't rechecked ruby structures and if we can use rt:first-child to notice it's the first child and above.)

Then, everything else can go in B - and needs a title and a help_text to make it clear what it achieves :) ("Make ruby in CJK books look better" ? :)

**Comment by davidvelosa** [comment]
>I'm still unsure what you're focusing on:

Lol, good point. It was a mix of both. And now taking your explanation and points in account:

First, I was checking on some Japanese books settings, all seem to have `line-height: 2em` set by author. So there's a lot of 'standard' space between lines for working with books that include ruby. Whereas on latin character books is 1.2
- the only thing I would see entering in conflict here, is when you as user set a default "Line Spacing", and I suspect that's around 120 in most cases (quick idea: include on ruby style tweaks an optional force line-height: 2 / double space as well?)

**SOLUTION TO A:**

Taking in account publisher defines 1.5 - 2 line height. Not including `<rt>` styling. And reducing font size to a happy half 45% (how 42% looks for you?). This because I don't know how many people uses Koreader in non e-ink screens, and I give you the reason that 40% might be too small for a pc screen, don't know about cellphones and I have no way to test. But on e-ink "paper like" screen 40% is totally perfect, and I quote myself from above:

>This is applicable to e-ink screens, in other types of screen the type pixel density can affect, but seeing Asian characters in a low density screen often requires bigger text sizes 🤷‍♂️, so this would be proportional.

In this case, I stand for a `line-height: 1.6` on  `rt, rubyBox[T=rt]` as well as a standard, I would say put it and wait for random feedback, if any. _Nobody notices good design but everybody judges a bad one ;)_  My reason is the space between a Main 'high' character and a 'low' ruby character, which get waaay too close at 1 or 1.2:

Line heights 1, 1.2, 1.6 from left to right
<p float="left">
  <img src="https://user-images.githubusercontent.com/78831040/130114259-ccf6b3ee-1e2a-46b7-96e3-596d9d6cac10.png" width="30%" />
  <img src="https://user-images.githubusercontent.com/78831040/130114266-ca5c2da5-b3bc-4b46-87c6-e77bd93d98c1.png" width="30%" /> 
  <img src="https://user-images.githubusercontent.com/78831040/130114280-60ee08ec-7944-43ce-9f0c-f2fdb96a7b18.png" width="30%" /> 
</p>



```css
rb, rubyBox[T=rb] {
     line-height: 1;
 }
 rt, rubyBox[T=rt] {
-    line-height: 1.2;
-    font-size: 50%;
+    line-height: 1.6;
+    font-size: 45%; 
     font-variant-east-asian: ruby;
     -cr-hint: text-selection-skip;
 }
```
**SOLUTIONS TO B:**

Here I would go with all the settings I previously commented you and give two alternatives (original font, sans serif font).
- Here as well, I would stand for font-weight: 400, because if you set a 200 weight on the main text and ruby follows this, ruby characters can become unreadable. And you have to take in account that ruby size font is 45% so the traces are leaner by more than half  (if the main font is 400, ruby can be "perceived" as 200 already at this point, because of the size. If on 200, then ruby 100) 
- Depending on the font, specially the serif styles, they risk of almost getting lost. With "Noto Sans CJK" that doesn't happen because the 'light' version at the end is not so light lol. 
- But I'll show you an example with "Shippori Mincho" on 200 which is lighter, and still, using 400 on ruby font will only help a bit, with ruby set on "Noto Sans CJK" the problem disappears

 <p float="left">
  <img src="https://user-images.githubusercontent.com/78831040/130118102-46b81548-1fc2-43c6-9be8-ee5c62933449.png" width="48%" />
  <img src="https://user-images.githubusercontent.com/78831040/130118115-50968ee0-162f-4ba3-9530-301a61659c76.png" width="48%" /> 
</p>



POSSIBLE NAMES AND SETTINGS for B:

ロ Stylize ruby - original font
help_text = Make ruby in CJK books look better with parent font

```css
rt {padding-bottom:2%}

rt, rubyBox[T=rt]{
     font-size: 40%;
     font-weight: 400;
     line-height:1;
}
```

ロ Stylize ruby - sans serif
help_text =  Make ruby in CJK books look better with Sans Serif font

```css
rt {padding-bottom:2%}

rt, rubyBox[T=rt]{
     font-family; “Noto Sans CJK SC”;
     font-size: 40%;
     font-weight: 400;
     line-height:1;
}
```

line-height:1.6 could be used in both Bs as well (taking in account the troubles that I previously mentioned of line-height:1), but the idea would be to give an alternative :) What you think? Then it would be something like this

ロ Stylize ruby - original font
```css
rt, rubyBox[T=rt]{
     font-size: 40%;
     font-weight: 400;
     line-height:1.6;
}
```

```css
rt, rubyBox[T=rt]{
     font-family; “Noto Sans CJK SC”;
     font-size: 40%;
     font-weight: 400;
     line-height:1.6;
}
```

**Comment by poire-z** [comment]
Not enough brain power to focus on your whole post at the moment :)

Just mentionning that for B / style tweaks, they are cumulative - and we can't have enabling one auto-disabling an other.
So, your tweaks as they look similar in parts, could be each bits with only the different parts, and you could toggle each subparts, giving more combinations and flexibility, i.e.:
```
[x] Stylize ruby - {font-size, font-weight, line-height:1}
[x] Ruby use a Sans font - {font-family}
[x] Ruby with larger lignt height- {line-height:1.6} with a higher priority so it overrides the line-height:1 of the first
```
(with a bit better names than mine :)

**Comment by davidvelosa** [comment]
Sorry, I know I extend a bit on my explanations 😅😂

Sounds good for me! :) maybe add this one as well? (need to read first third of previous post):
`[x] Force double line height - {body:line-height:2}`

**Comment by poire-z** [comment]
> Some samples... (after doing the samples I just realized that latin characters do something to the line, but in 200 is almost imperceptible)

Not sure why. Thought it might be because we pick latin and CJK glyphs each from either the main font or the fallback font - but quick looking at the code, this should not have any impact on the resulting line-height, which is decided from the main font before looking at glyphs and seeing the need to use another font.

> Is it possible for you to detect ruby tags _on a file_

When reading that the other day, thought you meant detecting them in a paragraph - so to set the paragraph line-height only - not in a whole file (which feels even more excessive and wrong).
If we were able to (not saying we are, just asking), so to ensure the same ilne-height to all lines of a paragraph which may have only a single line with ruby - would it really be fine to have this paragraph with auto x1.5 - with possibly the next paragraph without any ruby having the normal/smaller line-height. I feel it would look a bit odd. So may be forget about auto-making-sure-ruby-fits-when-met and trust the publisher/user ?

> **SOLUTION TO A:**
> And reducing font size to a happy half 45% (how 42% looks for you?).
> I stand for a `line-height: 1.6`  [...] My reason is the space between a Main 'high' character and a 'low' ruby character, which get waaay too close at 1 or 1.2:

So, you prefer them smaller but further from the base ?
No objection to `line-height: 1.6; font-size: 45/42%;` if that's how you expect them - it looks ok to my non-ruby-reader eyes.
Btw, for reading CJK glyphs (complex with all the little variations) vs. latin glyphs (simpler, no doubts), do readers will always require a larger font size for the same confort of reading ?

> **SOLUTIONS TO B:**

Again, you're more free to propose whatever there :) But I'm fine with your ideas.
We'll probably have them in a submenu in there, so your 3+ tweaks don't make that menu goes to 6 items and hide more of the text below. In a submenu, they will be 3/4 items, leaving some large enough room below to see how they affect the text.
![image](https://user-images.githubusercontent.com/24273478/130315040-e8e3118c-efac-414d-92e3-acb3d953c7ed.png)
The last item will be replaced with (and moved into) a `Ruby >` submenu.

But about `rt {padding-bottom:2%}` : 
- this is to move it further from the text right ? Which is what `line-height: 1.6` already achieves, right ? So, why the need for this additional/different way to add more ? Just so it's not also added above the rt? Or else?
- 2% seems little, do you really see some effect ?
- `rt {` only, not `rt, rubyBox[T=rt] {` ?

**Comment by davidvelosa** [comment]
>Not sure why. Thought it might be because we pick latin and CJK glyphs each from either the main [...]

I might have a rough idea why. But explanation can get a bit confusing by now, long story short, the height from different types can vary (if just a bit) and apparently latin fonts can have a tad more space (let's say 1px?) up and down. But as I said this varies from font to font, is not something you can find in the code. Some image I found below.

![image](https://user-images.githubusercontent.com/78831040/130329453-b5f62556-3697-4d79-b76b-3294fae28726.png)

>So may be forget about auto-making-sure-ruby-fits-when-met and trust the publisher/user ?

I don't trust anybody lol, but I think you are right on this one ;) 

One question about this basic settings that probably you can clear out to me:
I have always found interesting (and kind of odd, to tell you the truth) that justification / text align settings are not on the typography or line height settings, but you have to dive into the style tweaks menu to find it, when for me is something so basic and easily findable even in Word. So why hide it? Is there any reason for this? My question is because I was reading about Chinese typography (to answer your next question) and Full justification is the standard, in Chinese at least (here the question popped out). For us western people is common to use Left or justified in long texts and center as well (maybe in poems?). Is just a question out of curiosity :)

>So, you prefer them smaller but further from the base ?

Yes, totally. I'm gonna drop some samples below.

ruby text-size: 40% to left and 50% to the right
(LINE HEIGHT: 1, line spacing 90) :
<p float="left">
  <img src="https://user-images.githubusercontent.com/78831040/130331011-08cbe328-08fd-4dcd-8fff-65adb243938e.png" width="48%" />
  <img src="https://user-images.githubusercontent.com/78831040/130331018-70809329-3997-46f5-b8a3-f5665cad9e7d.png" width="48%" /> 
</p>

ruby text-size: 40% to left and 50% to the right
(LINE-HEIGHT: 1.6, line spacing 90) :
<p float="left">
  <img src="https://user-images.githubusercontent.com/78831040/130331106-997a0ecf-e6ca-41f0-8f3d-399bd0e16ec1.png" width="45%" />
  <img src="https://user-images.githubusercontent.com/78831040/130331107-7eaaade2-904a-40c9-ab6f-ded7b67fc353.png" width="45%" /> 
</p>

Throwing this one just because it looks nice :P (here you can start to see how ruby and main text spacing start to vary just because Line spacing is higher)
ruby text-size: 40%, line-height: 1.6, LINE SPACING 90 on the right, LINE SPACING 120 on the left) :
<p float="left">
  <img src="https://user-images.githubusercontent.com/78831040/130331106-997a0ecf-e6ca-41f0-8f3d-399bd0e16ec1.png" width="45%" /> 
  <img src="https://user-images.githubusercontent.com/78831040/130331230-3322ac68-f94f-4643-929c-12fcfc2cdeb1.png" width="45%" />
</p>

>Btw, for reading CJK glyphs (complex with all the little variations) vs. latin glyphs (simpler, no doubts), do readers will always require a larger font size for the same confort of reading ?

This is an interesting and complex one to answer, specially when I'm not a hard Asian language reader yet, but from my point of view, yes. Maybe a Chinese person won't have a problem reading a 12pt size CJK text, but what I'm certain of is that reading the same text at 16pt is going to be less fatiguing to the eye (having the right combination of text size and line height). Specially because of what you say, CJK gliphs are way more complex and smaller, and this is a hard (and slower) to read combination.
Another thing is that in western we tend to use 12pt or smaller fonts (9pt to 12pt for text body) whereas, on the east the tendency might be the opposite (12-14-16pts) but take it by a grain of salt, I haven't done enough research. :)

>Again, you're more free to propose whatever there :) But I'm fine with your ideas.
We'll probably have them in a submenu in there, so your 3+ tweaks don't make that menu goes to 6 items and hide more of the text below. In a submenu, they will be 3/4 items, leaving some large enough room below to see how they affect the text.

For me sounds great! What do you think of adding a Hold for more info on Ruby? with some help_text, because for me the rough settings from tweaks came from the back of my mind, but probably is not like that for everybody. So specifying why you would want to use the settings and changing the line spacing might, be a good idea. Would be user friendly and not imposing :)



>But about rt {padding-bottom:2%} :
    this is to move it further from the text right ? Which is what line-height: 1.6 already achieves, right ? So, why the need for this additional/different way to add more ? Just so it's not also added above the rt? Or else?

I experimented some more with the padding and is giving me irregularities that I saw until today, so let's forget this one as well. :)

The idea of this was to give more space to the characters when Line spacing is below 100, say 80. Anyways a good effect would be achieved changing line-height: 1.6 to line-height:2 on `rt, rubyBox[T=rt] {`, only if you want to close the line spacing so much, and characters start to overlap. But personally I might be just fine with line-height:1.6 Line spacing 120-150 for my regular use, the day I close the lines so much, most likely I won't be using ruby anyways :) The name of the function would be "increase space between ruby and main text??". This would come with the price of making a bit irregular the lines with and without ruby, but it's a tweak, isn't it?

Line spacing 80 (`line-height:1.6` on the left, `line-height:2` on the right)
<p float="left">
  <img src="https://user-images.githubusercontent.com/78831040/130337358-2b8a78fd-32ff-4827-9779-1c52e65c7051.png" width="45%" />
  <img src="https://user-images.githubusercontent.com/78831040/130337361-2fc36984-840a-4273-9dff-791b8d2bad82.png" width="45%" /> 
</p>

**Comment by poire-z** [comment]
> One question about this basic settings that probably you can clear out to me:
I have always found interesting (and kind of odd, to tell you the truth) that justification / text align settings are not on the typography or line height settings, but you have to dive into the style tweaks menu to find it, when for me is something so basic and easily findable even in Word. So why hide it? 

Because everything you see in the top and bottom menus are "global" settings (kerning, hinting, contrast, page margins - font size sets the size of the root node, hyphenation, typography lang...): they set some global settings that may or may not then be tweaked by CSS, our epub.css or the publisher embedded styles - that target specific elements (so, "local" vs "global").

Everything else you'd like to have are CSS that are/can/should _target specific elements_ by our epub.css or the publisher's CSS.
In our epub.css, we set `BODY {text-align: justify}` because that's how it looks in books.
A user wanting to have all/some parts of the book left aligned needs to decide if he wants `BODY {text-align: left }` or just `P {text-align: left}` - so style tweaks give the flexibility.
The CSS injection is handled for style tweaks. Having toggle/menus elsewhere like in the bottom menu for the most obvious ones would spread this CSS injection code a bit everywhere and would make  understanding what happens and why harder for the user, and our code more ugly :)
We're like browsers (we're a HTML/EPUB browser/renderer) - not a text editor - and you won't find a menu to align the text left or justified in Firefox :)

> here you can start to see how ruby and main text spacing start to vary just because Line spacing is higher

For info, in the code, I had added:
```c
if ( is_ruby_table )
   RENDER_RECT_SET_FLAG(fmt, NO_INTERLINE_SCALE_UP);
[...]
int interline_scale_factor = enode->getDocument()->getInterlineScaleFactor(); // that's our bottom LineSpacing %
if ( style->line_height.type != css_val_screen_px && interline_scale_factor != INTERLINE_SCALE_FACTOR_NO_SCALE ) {
    if ( RENDER_RECT_PTR_HAS_FLAG(fmt, NO_INTERLINE_SCALE_UP) && interline_scale_factor > INTERLINE_SCALE_FACTOR_NO_SCALE ) {
        // Don't scale up (for <ruby> content, so we can increase interline to make
        // the text breath without spreading ruby annotations on the space gained)
    }
    else {
        line_h = (line_h * interline_scale_factor) >> INTERLINE_SCALE_FACTOR_SHIFT;
    }
}
```
So, Line Spacing 80% will also scale down the ruby base & text line-height - but Line spacing 120% will let them as-is (100% of your specified `line-height: 1.6`) and will only increase the main text line-height.

> For me sounds great! What do you think of adding a Hold for more info on Ruby? with some help_text, because for me the rough settings from tweaks came from the back of my mind, but probably is not like that for everybody. So specifying why you would want to use the settings and changing the line spacing might, be a good idea. Would be user friendly and not imposing :)

Don't we already have that, when long-press on a style tweak ?:
<kbd>![image](https://user-images.githubusercontent.com/24273478/130350270-f9999166-9cfb-4d0f-8e38-cb77742a91a3.png)</kbd>

And we can also have a "About ruby", like we have:
<kbd>![image](https://user-images.githubusercontent.com/24273478/130350282-ad548b5a-1ec9-4e0a-9947-2bd43f0d7d49.png)</kbd>

**Comment by davidvelosa** [comment]
>We're like browsers (we're a HTML/EPUB browser/renderer) - not a text editor - and you won't find a menu to align the text left or justified in Firefox :)

But browsers don't force justify :), certainly books most of the times do yeah! Somehow I find things like Kerning or Word Spacing way more specific (and personally I feel much less like playing with them) than text align, points of view I guess. Anyways I find myself using the upper menu like 98% of the time :)

> So, Line Spacing 80% will also scale down the ruby base & text line-height - but Line spacing 120% will let them as-is (100% of your specified line-height: 1.6) and will only increase the main text line-height.

About this I can't say until I see, I would be more worried about lines between ruby and main text closing too much (the case of narrow Line spacing) than opening too much, it's always better to have breathing space for characters and whites than the opposite. 

>Don't we already have that, when long-press on a style tweak ?:

OMG this I didn't knew lol, it only works long pressing on tweaks

>And we can also have a "About ruby", like we have:

Exactly! to recommend the 1.5 or double spacing here and all our other conclusions :)

So at the end the tweaks (B) would be?:

- Original font -> force Sans Serif font on ruby
- Force regular weight font (400)
- Bigger ruby text size (I was thinking maybe somebody would like to keep things how they were before? don't know what you think :)
- `[x] Stylize ruby - {font-size, font-weight}`  I'm fine with this but what if you want to keep the weight and not the size and vice-versa? 
- More space between ruby lines?? (is it staying? not sure if it's necessary with the changes that are being made in A and the code you are adding on top)

**Comment by poire-z** [comment]
> But browsers don't force justify :), certainly books most of the times do yeah!

`Styles > epub.css` is our book-oriented User-Agent stylesheet, with `text-align: justify`, text-indent on P.
`Styles > html5.css` is like what most browsers do, `text-align: left`, no text-indent on P, spacing between P. As browsers do per default, but not really pretty when publishers has done no styling (or for home made EPUBs or viewing HTML files saved-as on browsers).

> Somehow I find things like Kerning or Word Spacing way more specific (and personally I feel much less like playing with them) than text align, points of view I guess. Anyways I find myself using the upper menu like 98% of the time :)

I understand. But what I was trying to explain is that our settings are technically oriented, mostly because that's how they work the best/clearest - and we expect users to know a bit about the technicalities of ebooks (or to just be fine with the default publisher settings :)
Having a **Text Align** `left|center|right|justified` in the bottom menu would have right and center rarely used (and work unexpected if RTL Arabic mixed with latin). And justified would make our chapter titles containg 2 or 3 words span all the line with words pushed to the margins. And it would hard-kill any publisher style, like epigraphs right aligned.

So, what you'd want is to map some curated-style tweaks to some bottom buttons - which is complex to build (just think: all the thinking you're putting now onto ruby, but x10 for all elements P BLOCKQUOTE H1 .. H2 list items...) in the hope it will work on most books - but it won't on some :) So, best for them to just be suggestions in `Style tweaks>`, and possibly to be fine-tuned per book with `Book style tweak` - but one needs to know CSS, use View HTML... which some of us do on each new book.
Also, I don't want to spread style tweaks from its menu up to various other menu or bottom buttons - as it would make it hard to understand what affects what.

> > So, Line Spacing 80% _will_ also scale down the ruby base & text line-height - but Line spacing 120% _will_ let

> About this I can't say until I see, 

My "will" were to mean "does" :) I was describing the current code's behaviour (so you can understand why may be what you find inconsistent did happen). So, you can already try & see.

>  I would be more worried about lines between ruby and main text closing too much (the case of narrow Line spacing) than opening too much

When Line Spacing decreases, we need to close all, in order for the the ruby to not be written over the above or below line. So, you `rt {line-height: 1.6}` will be scaled down.
When Line Spacing increases, we add space between lines, but we don't want the ruby to fly up and be in the middle (which could happen if we scale up your `rt {line-height: 1.6}` . We want to keep it near the glyph, so the NO_INTERLINE_SCALE_UP : your rb/rt line-height won't rise. If you want to spread the ruby further from its base, you need to set a higher line-height via CSS.

> OMG this I didn't knew lol, it only works long pressing on tweaks

What else but long-pressing? Single tap is for enabling, you don't need to see the help and CSS snippet once you're familiar and enabling them become a reflex.

> So at the end the tweaks (B) would be?:

As you wish, but don't make too many of them - 4/5 at most to leave room below. Users who want more tweaked tuning can make their own user style tweaks, yours will work as suggestions/examples/inspiration.

> Force regular weight font (400)

Not sure if this one needs to be an individual one - after your explanation, I understand its best, so you could include it in all your style tweaks (we won't in epub.css, as this is not per-specs and we should do as browsers by default).

> [x] Stylize ruby - {font-size, font-weight} I'm fine with this but what if you want to keep the weight and not the size and vice-versa?

I don't, I trust you style :) or I'll make my own :) font-weight is minor.

> Bigger ruby text size (I was thinking maybe somebody would like to keep things how they were before? don't know what you think :)

Why not, if you have room.

> More space between ruby lines?? (is it staying? not sure if it's necessary with the changes that are being made in A and the code you are adding on top)

(I'm not adding any new code - as explained above :)
Dunno what you think we'll add in A that will help with this? We're not changing any main text line-height only the rt one.
Our bottom Line Spacing progress buttons go from 70% to 130% - and ruby users need 1.6 or 2. If the publishers has not set them correctly, style tweaks to force all text to be 1.6 or 2 might be useful. Then, our Line Spacing buttons are for fine tuning these (it's a factor, so 110% will make your 2 be 2.2)

You can already play at organizing the menu and making the tweaks by editing your https://github.com/koreader/koreader/blob/c16d2712efb7fc1c9db7c6a03ec98d1daa280a8c/frontend/ui/data/css_tweaks.lua#L283-L314
(Hope it's easy to understand :)

**Comment by davidvelosa** [comment]
>But what I was trying to explain is that our settings are technically oriented, mostly because that's how they work the best/clearest - and we expect users to know a bit about the technicalities of ebooks (or to just be fine with the default publisher settings :)

I guessed this, of course you guys maintain the application and do a great job, and if something something works under your logic and makes your life easier is totally understandable, like I told you before and tell you now, you guys do a great job! no doubt about it! 👍👍👍 that;s what I mean when I include questions with implications and stuff, because I know there's a big work involved with anything on the coding world. And you are right, only the fact of installing koreader can involve technicality at some level.

>My "will" were to mean "does" :) I was describing the current code's behaviour (so you can understand why may be what you find inconsistent did happen). So, you can already try & see.

Ok I see. Yeah is tried already lol

>Not sure if this one needs to be an individual one - after your explanation, I understand its best, so you could include it in all your style tweaks (we won't in epub.css, as this is not per-specs and we should do as browsers by default).

>Dunno what you think we'll add in A that will help with this? We're not changing any main text line-height only the rt one.

Yeah, some confusion with all the discussion and the code you posted I suppose :) so probably it would be good to set it as an option as well. I know A will only decrease text size and change the line height in rt. So to be clear it would be like this:

**If A.**
```css
rt, rubyBox[T=rt]{
     font-size: 42%;
     line-height:1.6;
}
```

**Then B.**

`[x] Regular weight ruby font w/ current font`

`help_text=` Set a normal text weight on ruby text when using lighter or bolder fonts

```css
rt, rubyBox[T=rt]{
     font-weight: 400;
}
```

`[x] Stylize ruby w/ sans-serif font`

`help_text=` Use a sans serif font to display all ruby text for a more 'book-like' feeling

```css
rt, rubyBox[T=rt]{
     font-family; “Noto Sans CJK SC”;
     font-weight: 400;
}
```

`[x] Bigger ruby text size`

`help_text=` Augment ruby text size

```css
rt, rubyBox[T=rt]{
   font-size: 50%;
}
```

`[x] Bigger spacing between ruby lines`

`help_text=` When Line Spacing is less than 100, this helps keep ruby characters separated from the main text

```css
rt, rubyBox[T=rt]{
   line-height:2;
}
```

`>Ruby> About ruby`
Ruby characters are small glosses on the Asian languages to show the logographs' (Hanzi, Kanji, Hanja, etc) pronunciation.
When using ruby characters, the recommended Line spacing is  between 150-200.


>You can already play at organizing the menu and making the tweaks by editing your

I don't do .lua, but I will give it a look :)

**Comment by poire-z** [comment]
OK, added your **A** in https://github.com/koreader/crengine/commit/e1e0b3dae8edfbd051fd327b6f93aa106b54dd9e which should make it into tomorrow's nightly with #8165.

> I don't do .lua, but I will give it a look :)

If you have updated your https://github.com/koreader/koreader/blob/master/frontend/ui/data/css_tweaks.lua with your proposed style tweaks, feel free to update it there and propose a Pull request.
If not, just say and I'll do it with your suggestions above.

**Comment by davidvelosa** [comment]
Sorry, I haven't had too much time to play with it these days. Probably it will be faster if you do it, but would be something like this??


 ```lua
title = _("Ruby"),
            {
                id = "ruby_regular_wheight";
                title = _("Regular weight ruby font w/ current font"),
                description = _("Set a normal text weight on ruby text when using lighter or bolder fonts."),
                css = [[
rt, rubyBox[T=rt]{
     font-weight: 400;
}
                ]],
            },
                id = "ruby_sans_serif";
                title = _("Stylize ruby w/ sans-serif font"),
                description = _("Use a sans serif font to display all ruby text for a more 'book-like' feeling."),
                css = [[
rt, rubyBox[T=rt]{
     font-family; “Noto Sans CJK SC”;
     font-weight: 400;
}
                ]],
            },

 id = "ruby_sans_serif";
                title = _("Bigger ruby text size"),
                description = _("Augment ruby text size."),
                css = [[
rt, rubyBox[T=rt]{
   font-size: 50%;
}
                ]],
            },

 id = "ruby_sans_serif";
                title = _("Bigger spacing between ruby lines"),
                description = _("When Line Spacing is less than 100, this helps keep ruby characters separated from the main text."),
                css = [[
rt, rubyBox[T=rt]{
   line-height:2;
}
                ]],
            },
```

**Comment by poire-z** [comment]
Yes, with proper different `id=`, balanced `{ }` and indentation.
I'll do it tomorrow based on this snippet.

**Comment by poire-z** [comment]
Normal text:

![image](https://user-images.githubusercontent.com/24273478/131994737-f75fa019-0382-4ed1-a884-32d52933c4c8.png)

Shouldn't your:
```lua
                {
                    id = "ruby_line_height_larger";
                    title = _("Larger spacing between ruby lines"),
                    description = _("When Line Spacing is less than 100, this helps keep ruby characters separated from the main text."),
                    css = [[
rt, rubyBox[T=rt] {
    line-height: 2;
}
                    ]],
                },
```
which gives this that doesn't look much different than originally:

![image](https://user-images.githubusercontent.com/24273478/131994877-45b8ebbd-fe27-4d6e-8a16-f3b35e6b8e6c.png)

better be:
```css
body {
    line-height: 2;
}
```

![image](https://user-images.githubusercontent.com/24273478/131995167-771137f2-a6fd-43e7-b2f5-aaae452f102b.png)

as just a one step solution to have larger and even space between lines - and be able to further tune that down with our 70-130% Line Space widget ?

At 80%:
![image](https://user-images.githubusercontent.com/24273478/131995395-0f9b2ee9-c8ab-491b-b5aa-56ee8bcac107.png)

I would like to remove of of the items to limit them to 5:

![image](https://user-images.githubusercontent.com/24273478/131995761-98341274-5cf5-4b3b-a09a-9ea55da464cd.png)

May be the regular weight one could be removed and be just with the "sans-serif font", where you also included weight:400 ?
Or remove the About ruby or my ruby inline one.
Thought the ruby inline one could be of use when you don't care much and want even line spacing - but we could also have a Hide ruby text to make RUBY/RB inline and RT hidden.
So, may be these could be splitted into 2 submenus.

**Comment by davidvelosa** [comment]
>better be:
body {
    line-height: 2;
}

We can try. I mean, I didn't it propose before as this is a 'global setting', and I don't know what will imply forcing the body line height and then playing with the Line Spacing, so that's my reason to leave it in ruby, I see it breaking less stuff in the long run. Unless you say otherwise, of course

> May be the regular weight one could be removed and be just with the "sans-serif font", where you also included weight:400 ?

Good for me.

>Or remove the About ruby 

Can it be `Ruby (hold for more info) >` ? So it's one line less on the submenu (two less merging the regular weight with sans-serif), we don't lose the info and ruby inline can stay.

**Comment by poire-z** [comment]
> We can try. I mean, I didn't it propose before as this is a 'global setting', and I don't know what will imply forcing the body line height and then playing with the Line Spacing, so that's my reason to leave it in ruby, I see it breaking less stuff in the long run. Unless you say otherwise, of course

It would "break" everything that does not contain any ruby by making unwanted large interline space in all non-ruby asian and western bits of text.
But this being a style tweak, it's at the discretion of the user : it's available for if he reads a book with 95% of such ruby content - and can bear the 5% being too airy. If it's too much, he can just disable it back.
But at least, it's there as a one stop solution to some cases.
If it needs more adapatation, the user can make his own book style tweak targeting class names, and can use it as an inspiration.

I feel your 
```css
rt, rubyBox[T=rt] {
    line-height: 2;
}
```
does not bring much change (a small stylistic one, making the ruby a tad more airy) but no strong solution - but tell me if I'm wrong :) We can include both if they both make some sense.

**Comment by davidvelosa** [comment]
>It would "break" everything that does not contain any ruby by making unwanted large interline space in all non-ruby asian and western bits of text.

yeah, right?

>But this being a style tweak, it's at the discretion of the user : it's available for if he reads a book with 95% of such ruby content - and can bear the 5% being too airy. If it's too much, he can just disable it back.

That's where I feel like it would be helping the user "breaking" stuff lol.
Let's say I was reading only Japanese books for a while and forcing body line-height 2 would be wonderful, three months pass, but then when I come back to a Spanish book everything is forcing double line and I change Line Spacing and does nothing, then I have to dig into the style tweaks to look for what I broke because I don't remember what I changed. Then putting a `body` tweak on the `ruby` menu wouldn't be logic for me, and also would take longer to find. What do you think?

>I feel your
rt, rubyBox[T=rt] {
    line-height: 2;
}
does not bring much change (a small stylistic one, making the ruby a tad more airy) but no strong solution - but tell me if I'm wrong :) We can include both if they both make some sense.

Don't know if strong, just functional :) this in the extreme case scenario I decide to close the lines too much (70-80), and I need more like a "fix my chunked ruby lines" button. Both can be included, but I don't know about a `body` setting on the `ruby` menu, something to think about thought

**Comment by poire-z** [comment]
> then I have to dig into the style tweaks to look for what I broke because I don't remember what I changed. Then putting a body tweak on the ruby menu wouldn't be logic for me, and also would take longer to find. What do you think?

You'll remember when you see this large line spacing :)
And I don't think a user will "enable it on all books", he will just on books where it's needed.

Most of our tweaks are mostly to fix what the publisher missed, or counteract the design choices he made and that you don't share.
I expect that on books with ruby, he has done good CSS because it's needed to look good (and uneven line spacing, I don't find that good - do you see that in real paper books ?)

You added stylistic tweaks, which is fine - but nearly all our other tweaks are not that: they do kill a lot (_Ignore publisher font sizes_, _Ignore publisher line heights_, _Justify most/all text_ !): you try it, you see how you like it, if both white (the publisher with bad taste) and black (you the killer) don't work good enough for you, you go do dedicated tweaks, starting from white or black depending on which needs the less followup changes.

line-height:2 is probably of no use in any other context, so I think it's fine in a ruby submenu.
We could set it on P and LI (we do that for "Left align _most_ text") if you see that publishers properly use P for paragraphs of ruby text - so that TABLEs and other bits don't get too degraded.
We could even have a `Ruby > enlage lines spacing on most text` and `Ruby > enlage lines spacing on all text` if it feels we want a less and a more radical options, like we have elsewhere.

**Comment by davidvelosa** [comment]
>You'll remember when you see this large line spacing :)
And I don't think a user will "enable it on all books", he will just on books where it's needed.

Yeah you got a point

>line-height:2 is probably of no use in any other context, so I think it's fine in a ruby submenu.

I agree on that

>We could even have a Ruby > enlage lines spacing on most text and Ruby > enlage lines spacing on all text if it feels we want a less and a more radical options, like we have elsewhere.

I like this, and probably is clearer and looks better overall :)

BTW, did the original translation setting roll out? I just had to do an emergency re-install of the whole thing and disappeared in mine (don't mind doing the manual install but... :)

**Comment by Frenzie** [comment]
Sorry, what do you mean by original translation setting?

**Comment by davidvelosa** [comment]
The original thread issue, that was solved by @poire-z about a month ago by replacing `translator.lua` and `readertypography.lua`, I just broke my reader trying to do the same lol

**Comment by poire-z** [comment]
No, we didn't rolled it out, it's still there - and I still see Auto detect source language.
You don't need to do any replacement if you pick a recent KOReader.
Things may look different between what you had by replacing theese files with a work-in-progress version vs. what we ended up with after the PR discussion.

**Comment by davidvelosa** [comment]
>Things may look different between what you had by replacing theese files with a work-in-progress version vs. what we ended up with after the PR discussion.

Yep I realized, didn't pay attention to the first option

**Comment by poire-z** [comment]
OK, my proposal in #8189. Comments and rewording suggestion in #8189 please :)
